// This file was auto-generated by Fern from our API Definition.

/** Sort order by sequence_number. Defaults to 'asc'. */
export const SessionsListTurnEventsRequestOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type SessionsListTurnEventsRequestOrder =
    (typeof SessionsListTurnEventsRequestOrder)[keyof typeof SessionsListTurnEventsRequestOrder];
