// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../index.js";

export interface SessionsListTurnEventsResponse {
    data: TrueFoundryGateway.TurnOutputEvent[];
    pagination: TrueFoundryGateway.EventsTokenPagination;
}
