// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { DraftSession } from "../../../../../../../types/DraftSession.js";

export const DraftSessionsCreateResponse: core.serialization.ObjectSchema<
    serializers.internal.agents.DraftSessionsCreateResponse.Raw,
    TrueFoundryGateway.internal.agents.DraftSessionsCreateResponse
> = core.serialization.object({
    data: DraftSession,
});

export declare namespace DraftSessionsCreateResponse {
    export interface Raw {
        data: DraftSession.Raw;
    }
}
