// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { DraftSession } from "../../../../../../../types/DraftSession.js";

export const DraftSessionsUpdateResponse: core.serialization.ObjectSchema<
    serializers.internal.agents.DraftSessionsUpdateResponse.Raw,
    TrueFoundryGateway.internal.agents.DraftSessionsUpdateResponse
> = core.serialization.object({
    data: DraftSession,
});

export declare namespace DraftSessionsUpdateResponse {
    export interface Raw {
        data: DraftSession.Raw;
    }
}
