// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";

export const CreateSessionRequest: core.serialization.Schema<
    serializers.agents.CreateSessionRequest.Raw,
    TrueFoundryGateway.agents.CreateSessionRequest
> = core.serialization.object({
    agentName: core.serialization.property("agent_name", core.serialization.string()),
});

export declare namespace CreateSessionRequest {
    export interface Raw {
        agent_name: string;
    }
}
