// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         agent_spec: {
 *             model: {
 *                 name: "name"
 *             }
 *         }
 *     }
 */
export interface CreateDraftSessionRequest {
    /** Inline agent definition. */
    agent_spec: TrueFoundryGateway.internal.agents.CreateDraftSessionRequestAgentSpec;
    /** Optionally link the draft to an existing saved agent in the tenant. Omit for a standalone draft. */
    agent_name?: string;
}
