// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateDraftSessionRequest {
    /** Replacement inline spec; never cleared. */
    agent_spec?: TrueFoundryGateway.internal.agents.UpdateDraftSessionRequestAgentSpec;
}
