// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../index.js";

/**
 * Replacement inline spec; never cleared.
 */
export interface UpdateDraftSessionRequestAgentSpec {
    model: TrueFoundryGateway.Model;
    instructions?: string;
    messages?: TrueFoundryGateway.private_.agents.UpdateDraftSessionRequestAgentSpecMessagesItem[];
    mcpServers?: TrueFoundryGateway.McpServer[];
    responseFormat?: TrueFoundryGateway.ResponseFormat;
    skills?: TrueFoundryGateway.Skill[];
    config?: TrueFoundryGateway.RuntimeConfig;
    variables?: Record<string, string>;
}
