// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { PrivateClient } from "../resources/private/client/Client.js";
import { SessionsClient } from "../resources/sessions/client/Client.js";

export declare namespace AgentsClient {
    export type Options = BaseClientOptions;
}

export class AgentsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AgentsClient.Options>;
    protected _sessions: SessionsClient | undefined;
    protected _private: PrivateClient | undefined;

    constructor(options: AgentsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get sessions(): SessionsClient {
        return (this._sessions ??= new SessionsClient(this._options));
    }

    public get private(): PrivateClient {
        return (this._private ??= new PrivateClient(this._options));
    }
}
