// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { AgentsClient } from "../resources/agents/client/Client.js";

export declare namespace PrivateClient {
    export type Options = BaseClientOptions;
}

export class PrivateClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PrivateClient.Options>;
    protected _agents: AgentsClient | undefined;

    constructor(options: PrivateClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get agents(): AgentsClient {
        return (this._agents ??= new AgentsClient(this._options));
    }
}
