// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../../api/index.js";
import * as core from "../../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../../index.js";

export const SubscribeTurnRequest: core.serialization.Schema<
    serializers.private_.agents.SubscribeTurnRequest.Raw,
    TrueFoundryGateway.private_.agents.SubscribeTurnRequest
> = core.serialization.object({
    afterSequenceNumber: core.serialization.property("after_sequence_number", core.serialization.number().optional()),
});

export declare namespace SubscribeTurnRequest {
    export interface Raw {
        after_sequence_number?: number | null;
    }
}
