// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../../../../../../index.js";

/**
 * @example
 *     {
 *         response_id: "response_id",
 *         input: [{
 *                 type: "tool.approval",
 *                 execution_id: "execution_id",
 *                 tool_call_id: "tool_call_id",
 *                 approval: {
 *                     status: "allow"
 *                 }
 *             }]
 *     }
 */
export interface ResponsesSendMessageRequest {
    response_id: string;
    input: TruefoundryGateway.AgentApprovalDecisionMessage[];
}
