// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         agentSpec: {
 *             model: {
 *                 name: "name"
 *             }
 *         }
 *     }
 */
export interface CreateDraftSessionRequest {
    /** Optional customer request metadata (x-tfy-metadata) persisted as request_metadata at draft session creation. */
    tfyMetadata?: string;
    agentSpec: TrueFoundryGateway.AgentSpec;
    /** Optionally link the draft to an existing saved agent in the tenant. Omit for a standalone draft. */
    agentName?: string;
}
