// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         draftSessionId: "draftSessionId"
 *     }
 */
export interface GetDraftSessionsRequest {
    /** Draft session identifier. */
    draftSessionId: string;
}
