// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../../../index.js";

/**
 * @example
 *     {
 *         agentName: "agent_name",
 *         limit: 1,
 *         order: "asc",
 *         pageToken: "page_token",
 *         startTimestamp: "start_timestamp",
 *         endTimestamp: "end_timestamp"
 *     }
 */
export interface ListDraftSessionsRequest {
    /** Filter to drafts linked to this saved agent. Omit to list all of the caller-owned drafts. */
    agentName?: string | null;
    /** Page size. Defaults to 10, max 100. */
    limit?: number | null;
    /** Sort draft sessions by creation time. Defaults to "desc". */
    order?: TrueFoundryGateway.ListDraftSessionsOrder | null;
    /** Opaque token from a previous response `next_page_token`. */
    pageToken?: string | null;
    /** Inclusive lower bound on `created_at`. Defaults upstream to 30 min before `end_timestamp`. */
    startTimestamp?: string | null;
    /** Inclusive upper bound on `created_at`. Defaults upstream to now. */
    endTimestamp?: string | null;
}
