// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundryGateway from "../../../../src/api/index";
import { TrueFoundryGatewayClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("DraftSessionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    agent_spec: { model: { name: "name" } },
                    agent_name: "agent_name",
                    title: "title",
                    created_by_subject: { subject_id: "subject_id", subject_type: "subject_type" },
                    created_at: "created_at",
                    updated_at: "updated_at",
                },
            ],
            pagination: { next_page_token: "next_page_token", previous_page_token: "previous_page_token", limit: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    id: "id",
                    agent_spec: {
                        model: {
                            name: "name",
                        },
                    },
                    agent_name: "agent_name",
                    title: "title",
                    created_by_subject: {
                        subject_id: "subject_id",
                        subject_type: "subject_type",
                    },
                    created_at: "created_at",
                    updated_at: "updated_at",
                },
            ],
            pagination: {
                next_page_token: "next_page_token",
                previous_page_token: "previous_page_token",
                limit: 1,
            },
        };
        const page = await client.internal.agents.draftSessions.list({
            agent_name: "agent_name",
            limit: 1,
            order: "asc",
            page_token: "page_token",
            start_timestamp: "start_timestamp",
            end_timestamp: "end_timestamp",
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.list();
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.list();
        }).rejects.toThrow(TrueFoundryGateway.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.list();
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.list();
        }).rejects.toThrow(TrueFoundryGateway.UnprocessableEntityError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "name" } } };
        const rawResponseBody = {
            data: {
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ role: "user", content: "content" }],
                    mcp_servers: [
                        {
                            name: "name",
                            enable_tools: ["@all"],
                            disable_tools: ["@all"],
                            preload_tools: ["@all"],
                            require_approval_for_tools: ["@all"],
                        },
                    ],
                    response_format: { type: "text" },
                    skills: [{ fqn: "fqn", preload: true }],
                    config: { iteration_limit: 1 },
                    variables: { key: "value" },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                    subject_display_name: "subject_display_name",
                    subject_pat_name: "subject_pat_name",
                    subject_controller_name: "subject_controller_name",
                    subject_external_identity_slug: "subject_external_identity_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.internal.agents.draftSessions.create({
            agent_spec: {
                model: {
                    name: "name",
                },
            },
        });
        expect(response).toEqual({
            data: {
                id: "id",
                agent_spec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            role: "user",
                            content: "content",
                        },
                    ],
                    mcp_servers: [
                        {
                            name: "name",
                            enable_tools: ["@all"],
                            disable_tools: ["@all"],
                            preload_tools: ["@all"],
                            require_approval_for_tools: ["@all"],
                        },
                    ],
                    response_format: {
                        type: "text",
                    },
                    skills: [
                        {
                            fqn: "fqn",
                            preload: true,
                        },
                    ],
                    config: {
                        iteration_limit: 1,
                    },
                    variables: {
                        key: "value",
                    },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                    subject_display_name: "subject_display_name",
                    subject_pat_name: "subject_pat_name",
                    subject_controller_name: "subject_controller_name",
                    subject_external_identity_slug: "subject_external_identity_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.create({
                agent_spec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.create({
                agent_spec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGateway.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.create({
                agent_spec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.create({
                agent_spec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGateway.UnprocessableEntityError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.create({
                agent_spec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGateway.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ role: "user", content: "content" }],
                    mcp_servers: [
                        {
                            name: "name",
                            enable_tools: ["@all"],
                            disable_tools: ["@all"],
                            preload_tools: ["@all"],
                            require_approval_for_tools: ["@all"],
                        },
                    ],
                    response_format: { type: "text" },
                    skills: [{ fqn: "fqn", preload: true }],
                    config: { iteration_limit: 1 },
                    variables: { key: "value" },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                    subject_display_name: "subject_display_name",
                    subject_pat_name: "subject_pat_name",
                    subject_controller_name: "subject_controller_name",
                    subject_external_identity_slug: "subject_external_identity_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions/draftSessionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.internal.agents.draftSessions.get("draftSessionId");
        expect(response).toEqual({
            data: {
                id: "id",
                agent_spec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            role: "user",
                            content: "content",
                        },
                    ],
                    mcp_servers: [
                        {
                            name: "name",
                            enable_tools: ["@all"],
                            disable_tools: ["@all"],
                            preload_tools: ["@all"],
                            require_approval_for_tools: ["@all"],
                        },
                    ],
                    response_format: {
                        type: "text",
                    },
                    skills: [
                        {
                            fqn: "fqn",
                            preload: true,
                        },
                    ],
                    config: {
                        iteration_limit: 1,
                    },
                    variables: {
                        key: "value",
                    },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                    subject_display_name: "subject_display_name",
                    subject_pat_name: "subject_pat_name",
                    subject_controller_name: "subject_controller_name",
                    subject_external_identity_slug: "subject_external_identity_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions/draftSessionId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.get("draftSessionId");
        }).rejects.toThrow(TrueFoundryGateway.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions/draftSessionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.get("draftSessionId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ role: "user", content: "content" }],
                    mcp_servers: [
                        {
                            name: "name",
                            enable_tools: ["@all"],
                            disable_tools: ["@all"],
                            preload_tools: ["@all"],
                            require_approval_for_tools: ["@all"],
                        },
                    ],
                    response_format: { type: "text" },
                    skills: [{ fqn: "fqn", preload: true }],
                    config: { iteration_limit: 1 },
                    variables: { key: "value" },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                    subject_display_name: "subject_display_name",
                    subject_pat_name: "subject_pat_name",
                    subject_controller_name: "subject_controller_name",
                    subject_external_identity_slug: "subject_external_identity_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.internal.agents.draftSessions.update("draftSessionId");
        expect(response).toEqual({
            data: {
                id: "id",
                agent_spec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            role: "user",
                            content: "content",
                        },
                    ],
                    mcp_servers: [
                        {
                            name: "name",
                            enable_tools: ["@all"],
                            disable_tools: ["@all"],
                            preload_tools: ["@all"],
                            require_approval_for_tools: ["@all"],
                        },
                    ],
                    response_format: {
                        type: "text",
                    },
                    skills: [
                        {
                            fqn: "fqn",
                            preload: true,
                        },
                    ],
                    config: {
                        iteration_limit: 1,
                    },
                    variables: {
                        key: "value",
                    },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                    subject_display_name: "subject_display_name",
                    subject_pat_name: "subject_pat_name",
                    subject_controller_name: "subject_controller_name",
                    subject_external_identity_slug: "subject_external_identity_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.update("draftSessionId");
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.update("draftSessionId");
        }).rejects.toThrow(TrueFoundryGateway.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.update("draftSessionId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.internal.agents.draftSessions.update("draftSessionId");
        }).rejects.toThrow(TrueFoundryGateway.UnprocessableEntityError);
    });
});
