// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export type ActionRequiredEvent =
    | TrueFoundryGateway.AgentApprovalRequired
    | TrueFoundryGateway.AgentToolResponseRequired
    | TrueFoundryGateway.AgentMcpAuthRequired;
