// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentInternalToolCallInfo {
    type: TrueFoundryGateway.AgentInternalToolCallInfoType;
    mcpServerId: string;
    mcpServerName: string;
    originalToolName: string;
    isApprovalRequired?: boolean;
    isDeferred?: boolean;
    isClientSide?: boolean;
}
