// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export interface AgentRawToolCall extends TruefoundryGateway.ChatCompletionMessageToolCall {
    provider_specific_fields?: Record<string, unknown> | undefined;
}
