// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export interface AgentResponsesInlineAgent {
    model: string;
    instruction?: string | undefined;
    messages?: TruefoundryGateway.AgentResponsesInlineAgentMessagesItem[] | undefined;
    mcp_servers?: TruefoundryGateway.AgentMcpServerRequest[] | undefined;
    model_params?: TruefoundryGateway.AgentModelParams | undefined;
    response_format?: TruefoundryGateway.AgentResponsesFormat | undefined;
    iteration_limit?: number | undefined;
    skills?: TruefoundryGateway.AgentSkillMount[] | undefined;
    sandbox?: TruefoundryGateway.AgentResponsesInlineAgentSandbox | undefined;
    variables?: Record<string, string> | undefined;
    /** ID of a prior stored response. Pass to continue a stateful conversation. */
    previous_response_id?: string | undefined;
    input?: TruefoundryGateway.AgentResponsesInput | undefined;
}
