// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentCompletionUsage {
    completion_tokens: number;
    prompt_tokens: number;
    total_tokens: number;
    completion_tokens_details?: TrueFoundryGateway.AgentCompletionUsageCompletionTokensDetails;
    prompt_tokens_details?: TrueFoundryGateway.AgentCompletionUsagePromptTokensDetails;
    cache_read_input_tokens?: number;
    cache_creation_input_tokens?: number;
}
