// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export type AgentResponseStreamingOutputEvent =
    | TruefoundryGateway.AgentLlmMessageDelta
    | TruefoundryGateway.AgentToolMessage
    | TruefoundryGateway.AgentExecutionCreated
    | TruefoundryGateway.AgentExecutionDone
    | TruefoundryGateway.AgentExecutionError
    | TruefoundryGateway.AgentMcpAuthRequired
    | TruefoundryGateway.AgentMcpInitialize
    | TruefoundryGateway.AgentSandboxCreated
    | TruefoundryGateway.AgentApprovalRequired
    | TruefoundryGateway.AgentToolResponseRequired
    | TruefoundryGateway.AgentResponseCreated
    | TruefoundryGateway.AgentResponseDone;
