// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export interface AgentResponseFormatJsonSchema {
    type: "json_schema";
    json_schema: TruefoundryGateway.AgentResponseFormatJsonSchemaJsonSchema;
}
