// This file was auto-generated by Fern from our API Definition.

export const AgentResponseDoneCancellationReasonCancellationReason = {
    ServerExecutionTimeout: "server-execution-timeout",
    ClientCancelled: "client-cancelled",
} as const;
export type AgentResponseDoneCancellationReasonCancellationReason =
    (typeof AgentResponseDoneCancellationReasonCancellationReason)[keyof typeof AgentResponseDoneCancellationReasonCancellationReason];
