// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export type AgentLlmUserMessageContentOneItem =
    | TrueFoundryGateway.ChatCompletionContentPartText
    | TrueFoundryGateway.ChatCompletionContentPartImage
    | TrueFoundryGateway.ChatCompletionContentPartInputAudio
    | TrueFoundryGateway.ChatCompletionContentPartFile;
