// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentRawToolCall extends TrueFoundryGateway.ChatCompletionMessageToolCall {
    provider_specific_fields?: Record<string, unknown> | undefined;
}
