// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export interface AgentExecutionOverwriteContext {
    type: "agent.context.overwrite";
    execution_id: string;
    reason: "compaction";
    context: TruefoundryGateway.AgentExecutionOverwriteContextContextItem[];
    current_context_usage: TruefoundryGateway.AgentCompletionUsage;
    compaction_llm_usage: TruefoundryGateway.AgentCompletionUsage;
}
