// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentApprovalDecisionMessage {
    type: "tool.approval";
    execution_id: string;
    tool_call_id: string;
    approval: TrueFoundryGateway.AgentApprovalDecision;
}
