// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export type AgentResponseFormat =
    | TruefoundryGateway.AgentResponseFormatZero
    | TruefoundryGateway.AgentResponseFormatOne
    | TruefoundryGateway.AgentResponseFormatJsonSchema;
