// This file was auto-generated by Fern from our API Definition.

export interface AgentMcpServerAuthInfo {
    mcp_server_id: string;
    mcp_server_name: string;
    auth_url: string;
    thread_ids: string[];
}
