// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentResponseDoneCancelled {
    type: "response.done";
    status: "cancelled";
    cancellation_reason: TrueFoundryGateway.AgentResponseDoneCancelledCancellationReason;
}
