// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentConfig {
    iteration_limit: number;
    sandbox?: TrueFoundryGateway.AgentConfigSandbox;
    dynamic_sub_agents?: TrueFoundryGateway.AgentConfigDynamicSubAgents;
    context_management?: TrueFoundryGateway.AgentConfigContextManagement;
    generative_ui?: TrueFoundryGateway.AgentConfigGenerativeUi;
    ask_user_questions?: TrueFoundryGateway.AgentConfigAskUserQuestions;
}
