// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentResponsesInlineAgent {
    model: string;
    instruction?: string | undefined;
    messages?: TrueFoundryGateway.AgentResponsesInlineAgentMessagesItem[] | undefined;
    mcp_servers?: TrueFoundryGateway.AgentMcpServerRequest[] | undefined;
    model_params?: TrueFoundryGateway.AgentModelParams | undefined;
    response_format?: TrueFoundryGateway.AgentResponsesFormat | undefined;
    iteration_limit?: number | undefined;
    skills?: TrueFoundryGateway.AgentSkillMount[] | undefined;
    sandbox?: TrueFoundryGateway.AgentResponsesInlineAgentSandbox | undefined;
    variables?: Record<string, string> | undefined;
    /** ID of a prior stored response. Pass to continue a stateful conversation. */
    previous_response_id?: string | undefined;
    input?: TrueFoundryGateway.AgentResponsesInput | undefined;
}
