// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export interface AgentLlmUserMessage {
    role: "user";
    content: TruefoundryGateway.AgentLlmUserMessageContent;
}
