// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentExecutionDone {
    type: "agent.done";
    execution_id: string;
    output: TrueFoundryGateway.AgentAssistantMessage;
    parent?: TrueFoundryGateway.AgentParent | undefined;
}
