// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentMcpServerRequest {
    name: string;
    headers?: Record<string, string> | undefined;
    enable_all_tools: boolean;
    tools?: TrueFoundryGateway.AgentMcpTool[] | undefined;
    deferred: boolean;
}
