// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentSpec {
    model: TrueFoundryGateway.Model;
    instructions?: string;
    messages?: TrueFoundryGateway.AgentSpecMessagesItem[];
    mcpServers?: TrueFoundryGateway.McpServer[];
    responseFormat?: TrueFoundryGateway.ResponseFormat;
    skills?: TrueFoundryGateway.Skill[];
    config?: TrueFoundryGateway.RuntimeConfig;
    variables?: Record<string, string>;
}
