// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentResponsesFormatJsonSchema {
    type: "json_schema";
    json_schema: TrueFoundryGateway.AgentResponsesFormatJsonSchemaJsonSchema;
}
