// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export interface AgentResponsesNamedAgent {
    agent_name: string;
    variables?: Record<string, string> | undefined;
    /** ID of a prior stored response. Pass to continue a stateful conversation. */
    previous_response_id?: string | undefined;
    input?: TruefoundryGateway.AgentResponsesStatefulInput | undefined;
}
