// This file was auto-generated by Fern from our API Definition.

export interface AgentClientSideToolResponseMessage {
    type: "tool.client_side_response";
    execution_id: string;
    tool_call_id: string;
    content: string;
}
