// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface AgentConfigContextManagement {
    compaction: TrueFoundryGateway.AgentConfigContextManagementCompaction;
    largeToolResponse: TrueFoundryGateway.AgentConfigContextManagementLargeToolResponse;
}
