// This file was auto-generated by Fern from our API Definition.

export interface AgentMcpServerAuthInfo {
    mcpServerId: string;
    mcpServerName: string;
    authUrl: string;
    threadIds: string[];
}
