// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export interface AgentAssistantMessage extends TruefoundryGateway.AgentEnrichedAssistantMessage {
    type: "agent.message";
    execution_id: string;
    finish_reason?: TruefoundryGateway.AgentFinishReason | undefined;
    created_at?: number | undefined;
}
