// This file was auto-generated by Fern from our API Definition.

export interface AgentErrorResponseError {
    message: string;
    type?: string | undefined;
    code?: string | undefined;
    param?: string | undefined;
}
