// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface BaseThreadDoneEvent {
    parent?: TrueFoundryGateway.AgentParent;
    threadId: string;
    title: string;
}
