// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ChatCompletionContentPartImageImageUrl {
    url: string;
    detail?: TrueFoundryGateway.ChatCompletionContentPartImageImageUrlDetail;
}
