// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ChatCompletionMessageToolCall {
    id: string;
    type: "function";
    function: TrueFoundryGateway.ChatCompletionMessageToolCallFunction;
}
