// This file was auto-generated by Fern from our API Definition.

export const ChatCompletionContentPartImageImageUrlDetail = {
    Auto: "auto",
    Low: "low",
    High: "high",
} as const;
export type ChatCompletionContentPartImageImageUrlDetail =
    (typeof ChatCompletionContentPartImageImageUrlDetail)[keyof typeof ChatCompletionContentPartImageImageUrlDetail];
