// This file was auto-generated by Fern from our API Definition.

export const ChatCompletionMessageToolCallType = {
    Function: "function",
} as const;
export type ChatCompletionMessageToolCallType =
    (typeof ChatCompletionMessageToolCallType)[keyof typeof ChatCompletionMessageToolCallType];
