// This file was auto-generated by Fern from our API Definition.

/** Optional subject type used with created_by_subject_id. */
export const CreatedBySubjectType = {
    User: "user",
    Team: "team",
    Serviceaccount: "serviceaccount",
    Virtualaccount: "virtualaccount",
    ExternalIdentity: "external-identity",
    AgentIdentity: "agent-identity",
    Role: "role",
} as const;
export type CreatedBySubjectType = (typeof CreatedBySubjectType)[keyof typeof CreatedBySubjectType];
