// This file was auto-generated by Fern from our API Definition.

export interface CreatedBySubject {
    subject_id: string;
    subject_slug: string;
    subject_type: string;
    tenant_name: string;
}
