// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface DraftSession {
    type: "session/draft";
    id: string;
    agentSpec: TrueFoundryGateway.AgentSpec;
    agentName: string | null;
    title: string | null;
    createdBySubject: TrueFoundryGateway.Subject;
    createdAt: string;
    updatedAt: string;
}
