// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface DraftSessionAgentSpec {
    model: TrueFoundryGateway.AgentModelSpec;
    instructions?: string;
    messages?: TrueFoundryGateway.DraftSessionAgentSpecMessagesItem[];
    mcpServers?: TrueFoundryGateway.AgentMcpServerRequest[];
    responseFormat?: TrueFoundryGateway.AgentResponsesFormat;
    skills?: TrueFoundryGateway.AgentSkillMount[];
    config?: TrueFoundryGateway.AgentConfig;
    variables?: Record<string, string>;
}
