// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface DraftSessionAgentSpec {
    model: TrueFoundryGateway.AgentModelSpec;
    instructions?: string | undefined;
    messages?: TrueFoundryGateway.DraftSessionAgentSpecMessagesItem[] | undefined;
    mcp_servers?: TrueFoundryGateway.AgentMcpServerRequest[] | undefined;
    response_format?: TrueFoundryGateway.AgentResponsesFormat | undefined;
    skills?: TrueFoundryGateway.AgentSkillMount[] | undefined;
    config?: TrueFoundryGateway.AgentConfig | undefined;
    variables?: Record<string, string> | undefined;
}
