// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface EventsTokenPagination {
    next_page_token?: string;
    previous_page_token?: string;
    limit: number;
    order: TrueFoundryGateway.EventsTokenPaginationOrder;
}
