// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ExtendedChunkDeltaToolCall extends TrueFoundryGateway.ChatCompletionChunkDeltaToolCall {
    toolInfo?: TrueFoundryGateway.ToolInfo;
    providerSpecificFields?: Record<string, unknown>;
}
