// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface InlineMcpServer {
    name: string;
    enableTools?: TrueFoundryGateway.InlineMcpServerEnableToolsItem[];
    disableTools?: TrueFoundryGateway.InlineMcpServerDisableToolsItem[];
    preloadTools?: TrueFoundryGateway.InlineMcpServerPreloadToolsItem[];
    requireApprovalForTools?: TrueFoundryGateway.InlineMcpServerRequireApprovalForToolsItem[];
    preload?: boolean;
    type: "inline";
    url: string;
}
