// This file was auto-generated by Fern from our API Definition.

/** Sort draft sessions by creation time. Defaults to "desc". */
export const ListDraftSessionsOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListDraftSessionsOrder = (typeof ListDraftSessionsOrder)[keyof typeof ListDraftSessionsOrder];
