// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ListSessionEventsResponse {
    data: TrueFoundryGateway.SessionEventItem[];
    pagination: TrueFoundryGateway.TokenPagination;
}
