// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ListEventsResponse {
    data: TrueFoundryGateway.TurnEvent[];
    pagination: TrueFoundryGateway.TokenPagination;
}
