// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface McpAuthRequiredEvent extends TrueFoundryGateway.BaseMcpAuthRequiredEvent {
    type: "mcp.auth_required";
    mcpServers: TrueFoundryGateway.McpServerAuthInfo[];
}
