// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface McpAuthRequiredEvent {
    type: "mcp.auth_required";
    /** Unique identifier for the event */
    id: string;
    created_at: string;
    servers: TrueFoundryGateway.AgentMcpServerAuthInfo[];
    thread_id?: string;
}
