// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface McpInitializeEvent {
    type: "mcp.initialize";
    /** Unique identifier for the event */
    id: string;
    createdAt: string;
    threadId: string;
    content: TrueFoundryGateway.McpInitializationInfo[];
    sequenceNumber: number;
}
