// This file was auto-generated by Fern from our API Definition.

export const ModelMessageEventType = {
    ModelMessage: "model.message",
} as const;
export type ModelMessageEventType = (typeof ModelMessageEventType)[keyof typeof ModelMessageEventType];
