// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ModelMessage {
    audio?: TrueFoundryGateway.ModelMessageAudio | undefined;
    content?: TrueFoundryGateway.ModelMessageContent | undefined;
    function_call?: TrueFoundryGateway.ModelMessageFunctionCall | undefined;
    name?: string | undefined;
    refusal?: string | undefined;
    thinking_blocks?: TrueFoundryGateway.ModelMessageThinkingBlocksItem[] | undefined;
    tool_calls?: TrueFoundryGateway.AgentEnrichedToolCall[] | undefined;
    type: "model.message";
    /** Unique identifier for the event */
    id: string;
    thread_id: string;
    finish_reason?: TrueFoundryGateway.AgentFinishReason | undefined;
    created_at: string;
    usage?: TrueFoundryGateway.ModelMessageUsage | undefined;
}
