// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ModelMessageEvent {
    content?: TrueFoundryGateway.ModelMessageEventContent | null;
    name?: string;
    refusal?: string | null;
    reasoningContent?: string;
    toolCalls?: TrueFoundryGateway.ToolCall[];
    type: TrueFoundryGateway.ModelMessageEventType;
    /** Unique identifier for the event */
    id: string;
    threadId: string;
    finishReason?: TrueFoundryGateway.FinishReason | null;
    createdAt: string;
    usage?: TrueFoundryGateway.ModelMessageUsage;
}
