// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ModelParams {
    maxTokens?: number;
    temperature?: number;
    topP?: number;
    topK?: number;
    parallelToolCalls?: boolean;
    reasoningEffort?: TrueFoundryGateway.ModelParamsReasoningEffort;
}
