// This file was auto-generated by Fern from our API Definition.

export interface ModelMessageEventUsageInputTokensBreakdown {
    harness: number;
    skills: number;
    instructions: number;
    tool_definitions: number;
    messages: number;
}
