// This file was auto-generated by Fern from our API Definition.

import type * as TruefoundryGateway from "../index.js";

export interface NamedAgentRunInput {
    /** ID of a prior stored response. Pass to continue a stateful conversation. */
    previous_response_id?: string | undefined;
    variables?: Record<string, string> | undefined;
    skills?: TruefoundryGateway.AgentSkillMount[] | undefined;
    input?: TruefoundryGateway.AgentConversationInputMessage[] | undefined;
    agent_name: string;
}
