// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

/**
 * Defaults to 'auto' (chain to session last turn). Use 'null' for the session's first turn.
 */
export type PreviousTurnIdInput = TrueFoundryGateway.PreviousTurnIdInputZero | string;
