// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface RegistryMcpServer {
    name: string;
    enableTools?: TrueFoundryGateway.RegistryMcpServerEnableToolsItem[];
    disableTools?: TrueFoundryGateway.RegistryMcpServerDisableToolsItem[];
    preloadTools?: TrueFoundryGateway.RegistryMcpServerPreloadToolsItem[];
    requireApprovalForTools?: TrueFoundryGateway.RegistryMcpServerRequireApprovalForToolsItem[];
    preload?: boolean;
    type: "truefoundry-mcp-registry";
}
