// This file was auto-generated by Fern from our API Definition.

export const ResponseFormatJsonSchemaType = {
    JsonSchema: "json_schema",
} as const;
export type ResponseFormatJsonSchemaType =
    (typeof ResponseFormatJsonSchemaType)[keyof typeof ResponseFormatJsonSchemaType];
