// This file was auto-generated by Fern from our API Definition.

export const ResponseFormatOneType = {
    JsonObject: "json_object",
} as const;
export type ResponseFormatOneType = (typeof ResponseFormatOneType)[keyof typeof ResponseFormatOneType];
