// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export type ResponseFormat =
    | TrueFoundryGateway.ResponseFormat.Text
    | TrueFoundryGateway.ResponseFormat.JsonObject
    | TrueFoundryGateway.ResponseFormat.JsonSchema;

export namespace ResponseFormat {
    export interface Text extends TrueFoundryGateway.ResponseFormatText {
        type: "text";
    }

    export interface JsonObject extends TrueFoundryGateway.ResponseFormatJsonObject {
        type: "json_object";
    }

    export interface JsonSchema extends TrueFoundryGateway.ResponseFormatJsonSchema {
        type: "json_schema";
    }
}
