// This file was auto-generated by Fern from our API Definition.

export const ResponseFormatZeroType = {
    Text: "text",
} as const;
export type ResponseFormatZeroType = (typeof ResponseFormatZeroType)[keyof typeof ResponseFormatZeroType];
