// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface RuntimeConfig {
    iterationLimit?: number;
    sandbox?: TrueFoundryGateway.SandboxConfig;
    dynamicSubAgents?: TrueFoundryGateway.DynamicSubAgentsConfig;
    contextManagement?: TrueFoundryGateway.ContextManagementConfig;
    generativeUi?: TrueFoundryGateway.GenerativeUiConfig;
    askUserQuestions?: TrueFoundryGateway.AskUserQuestionsConfig;
}
