// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface RuntimeConfig {
    iterationLimit: number;
    sandbox?: TrueFoundryGateway.RuntimeConfigSandbox;
    dynamicSubAgents?: TrueFoundryGateway.RuntimeConfigDynamicSubAgents;
    contextManagement: TrueFoundryGateway.RuntimeConfigContextManagement;
    generativeUi?: TrueFoundryGateway.RuntimeConfigGenerativeUi;
    askUserQuestions?: TrueFoundryGateway.RuntimeConfigAskUserQuestions;
}
