// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface SandboxConfig {
    enabled: boolean;
    fileDownloads?: boolean;
    networkPolicy?: TrueFoundryGateway.SandboxNetworkPolicy;
}
