// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface SequencedTurnStreamingOutputEventContextItemApproval {
    type: "user.tool_approval";
    tool_call_id: string;
    approval: TrueFoundryGateway.AgentApprovalDecision;
}
