// This file was auto-generated by Fern from our API Definition.

export interface SequencedTurnStreamingOutputEventFunctionCall {
    name?: string | undefined;
    arguments?: string | undefined;
}
