// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface SequencedTurnPersistedEvent {
    audio?: TrueFoundryGateway.SequencedTurnPersistedEventAudio | undefined;
    content?: TrueFoundryGateway.AgentMcpInitializationInfo[] | undefined;
    function_call?: TrueFoundryGateway.SequencedTurnPersistedEventFunctionCall | undefined;
    name?: string | undefined;
    refusal?: string | undefined;
    thinking_blocks?: TrueFoundryGateway.SequencedTurnPersistedEventThinkingBlocksItem[] | undefined;
    tool_calls?: TrueFoundryGateway.AgentToolCallRef[] | undefined;
    type?: "tool.response_required" | undefined;
    /** Unique identifier for the event */
    id?: string | undefined;
    thread_id?: string | undefined;
    finish_reason?: TrueFoundryGateway.AgentFinishReason | undefined;
    created_at?: string | undefined;
    usage?: TrueFoundryGateway.SequencedTurnPersistedEventUsage | undefined;
    tool_call_id?: string | undefined;
    agent_info?: TrueFoundryGateway.AgentInfo | undefined;
    parent?: TrueFoundryGateway.AgentParent | undefined;
    title?: string | undefined;
    output?: TrueFoundryGateway.ModelMessage | undefined;
    status?: "error" | undefined;
    error?: string | undefined;
    servers?: TrueFoundryGateway.AgentMcpServerAuthInfo[] | undefined;
    sandbox_id?: string | undefined;
    sequence_number: number;
}
