// This file was auto-generated by Fern from our API Definition.

export interface SessionSubject {
    subject_id: string;
    subject_type: string;
    subject_slug?: string;
    subject_display_name?: string;
    subject_pat_name?: string;
    subject_controller_name?: string;
    subject_external_identity_slug?: string;
}
