// This file was auto-generated by Fern from our API Definition.

/** Filter by session type. Omit to include both saved sessions and drafts. */
export const SessionType = {
    Session: "session",
    SessionDraft: "session/draft",
} as const;
export type SessionType = (typeof SessionType)[keyof typeof SessionType];
