// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface Session {
    type: "session";
    id: string;
    agentName: string;
    title?: string | null;
    createdBySubject: TrueFoundryGateway.Subject;
    createdAt: string;
    updatedAt: string;
}
