// This file was auto-generated by Fern from our API Definition.

export interface SkillMount {
    /** Fully qualified name of the agent skill version. */
    fqn: string;
    /** If true, the SKILL.md content is injected into the agent context. */
    preload?: boolean;
}
