// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ThreadDoneEvent {
    type: "thread.done";
    /** Unique identifier for the event */
    id: string;
    createdAt: string;
    parent?: TrueFoundryGateway.AgentParent;
    state: TrueFoundryGateway.ThreadState;
    threadId: string;
    title: string;
}
