// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ThreadCreatedEvent {
    /** Unique identifier for the event */
    id: string;
    agentInfo: TrueFoundryGateway.AgentInfo;
    createdAt: string;
    parent: TrueFoundryGateway.AgentParent;
    threadId: string;
    title: string;
}
