// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export type ThreadState = TrueFoundryGateway.ThreadState.Done | TrueFoundryGateway.ThreadState.Error;

export namespace ThreadState {
    export interface Done extends TrueFoundryGateway.ThreadStateDone {
        status: "done";
    }

    export interface Error extends TrueFoundryGateway.ThreadStateError {
        status: "error";
    }
}
