// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ThreadDoneEvent extends TrueFoundryGateway.BaseThreadDoneEvent {
    type: "thread.done";
    /** Unique identifier for the event */
    id: string;
    createdAt: string;
    state: TrueFoundryGateway.ThreadState;
}
