// This file was auto-generated by Fern from our API Definition.

export interface TokenPagination {
    next_page_token?: string | undefined;
    previous_page_token?: string | undefined;
    limit: number;
}
