// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface ToolApprovalRequiredEvent {
    type: "tool.approval_required";
    /** Unique identifier for the event */
    id: string;
    createdAt: string;
    threadId: string;
    toolCalls: TrueFoundryGateway.AgentToolCallRef[];
}
