// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export type ToolInfo = TrueFoundryGateway.ToolInfo.TruefoundrySystem | TrueFoundryGateway.ToolInfo.Mcp;

export namespace ToolInfo {
    export interface TruefoundrySystem extends TrueFoundryGateway.TrueFoundrySystemToolInfo {
        type: "truefoundry-system";
    }

    export interface Mcp extends TrueFoundryGateway.McpToolInfo {
        type: "mcp";
    }
}
