// This file was auto-generated by Fern from our API Definition.

export const ToolsSelectorTag = {
    All: "@all",
    ReadOnly: "@read-only",
} as const;
export type ToolsSelectorTag = (typeof ToolsSelectorTag)[keyof typeof ToolsSelectorTag];
