// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface TurnDoneCancelled {
    type: "turn.done";
    /** Unique identifier for the event */
    id: string;
    state: TrueFoundryGateway.TurnStateCancelled;
    createdAt: string;
    threadId?: string;
    sequenceNumber: number;
}
