// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface TurnDoneEvent {
    type: "turn.done";
    /** Unique identifier for the event */
    id: string;
    state: TrueFoundryGateway.TurnDoneEventState;
    createdAt: string;
    threadId?: string | null;
}
