// This file was auto-generated by Fern from our API Definition.

export const TurnStateRunningStatus = {
    Running: "running",
} as const;
export type TurnStateRunningStatus = (typeof TurnStateRunningStatus)[keyof typeof TurnStateRunningStatus];
