// This file was auto-generated by Fern from our API Definition.

export interface TurnMetrics {
    totalInputTokens: number;
    totalOutputTokens: number;
    totalTokens: number;
    totalCacheReadTokens?: number;
    totalCacheWriteTokens?: number;
    totalReasoningTokens?: number;
    totalCostInUsd?: number;
}
