// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface TurnOutputEvent {
    audio?: TrueFoundryGateway.TurnOutputEventAudio;
    content?: TrueFoundryGateway.AgentMcpInitializationInfo[];
    functionCall?: TrueFoundryGateway.TurnOutputEventFunctionCall;
    name?: string;
    refusal?: string;
    thinkingBlocks?: TrueFoundryGateway.TurnOutputEventThinkingBlocksItem[];
    toolCalls?: TrueFoundryGateway.AgentToolCallRef[];
    type?: "tool.response_required";
    /** Unique identifier for the event */
    id?: string;
    threadId?: string;
    finishReason?: TrueFoundryGateway.AgentFinishReason;
    createdAt?: string;
    usage?: TrueFoundryGateway.TurnOutputEventUsage;
    toolCallId?: string;
    agentInfo?: TrueFoundryGateway.AgentInfo;
    parent?: TrueFoundryGateway.AgentParent;
    title?: string;
    output?: TrueFoundryGateway.ModelMessageEvent;
    status?: "error";
    error?: string;
    servers?: TrueFoundryGateway.AgentMcpServerAuthInfo[];
    sandboxId?: string;
    sequenceNumber: number;
}
