// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface TurnEventUsage {
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens?: number;
    cacheWriteTokens?: number;
    inputTokensBreakdown: TrueFoundryGateway.TurnEventUsageInputTokensBreakdown;
}
