// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface TurnStateDoneOutput {
    audio?: TrueFoundryGateway.TurnStateDoneOutputAudio;
    content?: TrueFoundryGateway.TurnStateDoneOutputContent;
    function_call?: TrueFoundryGateway.TurnStateDoneOutputFunctionCall;
    name?: string;
    refusal?: string;
    thinking_blocks?: TrueFoundryGateway.TurnStateDoneOutputThinkingBlocksItem[];
    tool_calls?: TrueFoundryGateway.AgentEnrichedToolCall[];
    type: "model.message";
    /** Unique identifier for the event */
    id: string;
    thread_id: string;
    finish_reason?: TrueFoundryGateway.AgentFinishReason;
    created_at: string;
    usage?: TrueFoundryGateway.TurnStateDoneOutputUsage;
}
