// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export type TurnStreamingOutputEventContextItem =
    | TrueFoundryGateway.AgentLlmUserMessage
    | TrueFoundryGateway.AgentInternalEnrichedAssistantMessage
    | TrueFoundryGateway.AgentLlmToolMessage
    | TrueFoundryGateway.TurnStreamingOutputEventContextItemApproval;
