// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface TurnStreamingOutputEventContextItemApproval {
    type: "user.tool_approval";
    toolCallId: string;
    approval: TrueFoundryGateway.ApprovalDecision;
}
