// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface Turn {
    id: string;
    sessionId: string;
    firstTurnId: string;
    previousTurnId?: string;
    state: TrueFoundryGateway.TurnState;
    input: TrueFoundryGateway.TurnInputItem[];
    createdAt: string;
    updatedAt: string;
}
