// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface TurnStateDoneOutputUsage {
    input_tokens: number;
    output_tokens: number;
    cache_read_tokens?: number | undefined;
    cache_write_tokens?: number | undefined;
    input_tokens_breakdown: TrueFoundryGateway.TurnStateDoneOutputUsageInputTokensBreakdown;
}
