// This file was auto-generated by Fern from our API Definition.

export interface TurnStreamingEventUsageInputTokensBreakdown {
    harness: number;
    skills: number;
    instructions: number;
    toolDefinitions: number;
    messages: number;
}
