// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../index.js";

export interface UserToolApprovalEvent {
    threadId: string;
    toolCallId: string;
    approval: TrueFoundryGateway.ApprovalDecision;
}
