// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { ResponsesClient } from "../resources/responses/client/Client.js";

export declare namespace AgentClient {
    export type Options = BaseClientOptions;
}

export class AgentClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AgentClient.Options>;
    protected _responses: ResponsesClient | undefined;

    constructor(options: AgentClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get responses(): ResponsesClient {
        return (this._responses ??= new ResponsesClient(this._options));
    }
}
