// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundryGatewayTypes from "../../../../../src/api/index";
import { TrueFoundryGateway } from "../../../../../src/Client";
import { mockServerPool } from "../../../../mock-server/MockServerPool";

describe("DraftSessionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    type: "session/draft",
                    id: "id",
                    agent_spec: { model: { name: "name" } },
                    agent_name: "agent_name",
                    title: "title",
                    created_by_subject: {
                        subject_id: "subject_id",
                        subject_type: "subject_type",
                        subject_slug: "subject_slug",
                    },
                    created_at: "created_at",
                    updated_at: "updated_at",
                },
            ],
            pagination: { next_page_token: "next_page_token", previous_page_token: "previous_page_token", limit: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    type: "session/draft",
                    id: "id",
                    agentSpec: {
                        model: {
                            name: "name",
                        },
                    },
                    agentName: "agent_name",
                    title: "title",
                    createdBySubject: {
                        subjectId: "subject_id",
                        subjectType: "subject_type",
                        subjectSlug: "subject_slug",
                    },
                    createdAt: "created_at",
                    updatedAt: "updated_at",
                },
            ],
            pagination: {
                nextPageToken: "next_page_token",
                previousPageToken: "previous_page_token",
                limit: 1,
            },
        };
        const page = await client.private.agents.private.draftSessions.list({
            agentName: "agent_name",
            limit: 1,
            order: "asc",
            pageToken: "page_token",
            startTimestamp: "start_timestamp",
            endTimestamp: "end_timestamp",
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.list();
        }).rejects.toThrow(TrueFoundryGatewayTypes.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.list();
        }).rejects.toThrow(TrueFoundryGatewayTypes.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.list();
        }).rejects.toThrow(TrueFoundryGatewayTypes.NotFoundError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.list();
        }).rejects.toThrow(TrueFoundryGatewayTypes.UnprocessableEntityError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "name" } } };
        const rawResponseBody = {
            data: {
                type: "session/draft",
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ type: "user.message", content: "content" }],
                    mcp_servers: [{ name: "name", type: "truefoundry-mcp-registry" }],
                    response_format: { type: "text" },
                    skills: [{ fqn: "fqn" }],
                    variables: { key: "value" },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.private.agents.private.draftSessions.create({
            agentSpec: {
                model: {
                    name: "name",
                },
            },
        });
        expect(response).toEqual({
            data: {
                type: "session/draft",
                id: "id",
                agentSpec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            type: "user.message",
                            content: "content",
                        },
                    ],
                    mcpServers: [
                        {
                            name: "name",
                            type: "truefoundry-mcp-registry",
                        },
                    ],
                    responseFormat: {
                        type: "text",
                    },
                    skills: [
                        {
                            fqn: "fqn",
                        },
                    ],
                    variables: {
                        key: "value",
                    },
                },
                agentName: "agent_name",
                title: "title",
                createdBySubject: {
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                    subjectSlug: "subject_slug",
                },
                createdAt: "created_at",
                updatedAt: "updated_at",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.create({
                agentSpec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGatewayTypes.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.create({
                agentSpec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGatewayTypes.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.create({
                agentSpec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGatewayTypes.NotFoundError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.create({
                agentSpec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGatewayTypes.UnprocessableEntityError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_spec: { model: { name: "x" } } };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/agents/draft-sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.create({
                agentSpec: {
                    model: {
                        name: "x",
                    },
                },
            });
        }).rejects.toThrow(TrueFoundryGatewayTypes.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                type: "session/draft",
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ type: "user.message", content: "content" }],
                    mcp_servers: [{ name: "name", type: "truefoundry-mcp-registry" }],
                    response_format: { type: "text" },
                    skills: [{ fqn: "fqn" }],
                    variables: { key: "value" },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions/draftSessionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.private.agents.private.draftSessions.get("draftSessionId");
        expect(response).toEqual({
            data: {
                type: "session/draft",
                id: "id",
                agentSpec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            type: "user.message",
                            content: "content",
                        },
                    ],
                    mcpServers: [
                        {
                            name: "name",
                            type: "truefoundry-mcp-registry",
                        },
                    ],
                    responseFormat: {
                        type: "text",
                    },
                    skills: [
                        {
                            fqn: "fqn",
                        },
                    ],
                    variables: {
                        key: "value",
                    },
                },
                agentName: "agent_name",
                title: "title",
                createdBySubject: {
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                    subjectSlug: "subject_slug",
                },
                createdAt: "created_at",
                updatedAt: "updated_at",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions/draftSessionId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.get("draftSessionId");
        }).rejects.toThrow(TrueFoundryGatewayTypes.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/agents/draft-sessions/draftSessionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.get("draftSessionId");
        }).rejects.toThrow(TrueFoundryGatewayTypes.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            data: {
                type: "session/draft",
                id: "id",
                agent_spec: {
                    model: { name: "name" },
                    instructions: "instructions",
                    messages: [{ type: "user.message", content: "content" }],
                    mcp_servers: [{ name: "name", type: "truefoundry-mcp-registry" }],
                    response_format: { type: "text" },
                    skills: [{ fqn: "fqn" }],
                    variables: { key: "value" },
                },
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.private.agents.private.draftSessions.update("draftSessionId");
        expect(response).toEqual({
            data: {
                type: "session/draft",
                id: "id",
                agentSpec: {
                    model: {
                        name: "name",
                    },
                    instructions: "instructions",
                    messages: [
                        {
                            type: "user.message",
                            content: "content",
                        },
                    ],
                    mcpServers: [
                        {
                            name: "name",
                            type: "truefoundry-mcp-registry",
                        },
                    ],
                    responseFormat: {
                        type: "text",
                    },
                    skills: [
                        {
                            fqn: "fqn",
                        },
                    ],
                    variables: {
                        key: "value",
                    },
                },
                agentName: "agent_name",
                title: "title",
                createdBySubject: {
                    subjectId: "subject_id",
                    subjectType: "subject_type",
                    subjectSlug: "subject_slug",
                },
                createdAt: "created_at",
                updatedAt: "updated_at",
            },
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.update("draftSessionId");
        }).rejects.toThrow(TrueFoundryGatewayTypes.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.update("draftSessionId");
        }).rejects.toThrow(TrueFoundryGatewayTypes.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.update("draftSessionId");
        }).rejects.toThrow(TrueFoundryGatewayTypes.NotFoundError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGateway({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .patch("/v1/agents/draft-sessions/draftSessionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.private.agents.private.draftSessions.update("draftSessionId");
        }).rejects.toThrow(TrueFoundryGatewayTypes.UnprocessableEntityError);
    });
});
