// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../index.js";

/**
 * Inline agent definition.
 */
export interface CreateDraftSessionRequestAgentSpec {
    model: TrueFoundryGateway.AgentModelSpec;
    instructions?: string;
    messages?: TrueFoundryGateway.internal.agents.CreateDraftSessionRequestAgentSpecMessagesItem[];
    mcp_servers?: TrueFoundryGateway.AgentMcpServerRequest[];
    response_format?: TrueFoundryGateway.AgentResponsesFormat;
    skills?: TrueFoundryGateway.AgentSkillMount[];
    config?: TrueFoundryGateway.AgentConfig;
    variables?: Record<string, string>;
}
