// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../index.js";

/**
 * Replacement inline spec; never cleared.
 */
export interface UpdateDraftSessionRequestAgentSpec {
    model: TrueFoundryGateway.AgentModelSpec;
    instructions?: string;
    messages?: TrueFoundryGateway.internal.agents.UpdateDraftSessionRequestAgentSpecMessagesItem[];
    mcp_servers?: TrueFoundryGateway.AgentMcpServerRequest[];
    response_format?: TrueFoundryGateway.AgentResponsesFormat;
    skills?: TrueFoundryGateway.AgentSkillMount[];
    config?: TrueFoundryGateway.AgentConfig;
    variables?: Record<string, string>;
}
