// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpAuthRequiredEvent } from "./McpAuthRequiredEvent.js";
import { ToolApprovalRequiredEvent } from "./ToolApprovalRequiredEvent.js";
import { ToolResponseRequiredEvent } from "./ToolResponseRequiredEvent.js";

export const ActionRequiredEvent: core.serialization.Schema<
    serializers.ActionRequiredEvent.Raw,
    TrueFoundryGateway.ActionRequiredEvent
> = core.serialization.undiscriminatedUnion([
    ToolApprovalRequiredEvent,
    ToolResponseRequiredEvent,
    McpAuthRequiredEvent,
]);

export declare namespace ActionRequiredEvent {
    export type Raw = ToolApprovalRequiredEvent.Raw | ToolResponseRequiredEvent.Raw | McpAuthRequiredEvent.Raw;
}
