// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentSpecMessagesItem: core.serialization.ObjectSchema<
    serializers.AgentSpecMessagesItem.Raw,
    TrueFoundryGateway.AgentSpecMessagesItem
> = core.serialization.object({
    role: core.serialization.stringLiteral("user"),
    content: core.serialization.string(),
});

export declare namespace AgentSpecMessagesItem {
    export interface Raw {
        role: "user";
        content: string;
    }
}
