// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ChatCompletionContentPartFile } from "./ChatCompletionContentPartFile.js";
import { ChatCompletionContentPartImage } from "./ChatCompletionContentPartImage.js";
import { ChatCompletionContentPartInputAudio } from "./ChatCompletionContentPartInputAudio.js";
import { ChatCompletionContentPartText } from "./ChatCompletionContentPartText.js";

export const AgentLlmUserMessageContentOneItem: core.serialization.Schema<
    serializers.AgentLlmUserMessageContentOneItem.Raw,
    TrueFoundryGateway.AgentLlmUserMessageContentOneItem
> = core.serialization.undiscriminatedUnion([
    ChatCompletionContentPartText,
    ChatCompletionContentPartImage,
    ChatCompletionContentPartInputAudio,
    ChatCompletionContentPartFile,
]);

export declare namespace AgentLlmUserMessageContentOneItem {
    export type Raw =
        | ChatCompletionContentPartText.Raw
        | ChatCompletionContentPartImage.Raw
        | ChatCompletionContentPartInputAudio.Raw
        | ChatCompletionContentPartFile.Raw;
}
