// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentInternalEnrichedAssistantMessageAudio: core.serialization.ObjectSchema<
    serializers.AgentInternalEnrichedAssistantMessageAudio.Raw,
    TrueFoundryGateway.AgentInternalEnrichedAssistantMessageAudio
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace AgentInternalEnrichedAssistantMessageAudio {
    export interface Raw {
        id: string;
    }
}
