// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentConfigContextManagementLargeToolResponse: core.serialization.ObjectSchema<
    serializers.AgentConfigContextManagementLargeToolResponse.Raw,
    TrueFoundryGateway.AgentConfigContextManagementLargeToolResponse
> = core.serialization.object({
    enabled: core.serialization.boolean(),
    individual_tool_response_token_threshold: core.serialization.number(),
    total_tool_response_token_threshold: core.serialization.number(),
    preview_number_of_characters: core.serialization.number(),
});

export declare namespace AgentConfigContextManagementLargeToolResponse {
    export interface Raw {
        enabled: boolean;
        individual_tool_response_token_threshold: number;
        total_tool_response_token_threshold: number;
        preview_number_of_characters: number;
    }
}
