// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentSpecUserMessage: core.serialization.ObjectSchema<
    serializers.AgentSpecUserMessage.Raw,
    TrueFoundryGateway.AgentSpecUserMessage
> = core.serialization.object({
    type: core.serialization.stringLiteral("user.message"),
    content: core.serialization.string(),
});

export declare namespace AgentSpecUserMessage {
    export interface Raw {
        type: "user.message";
        content: string;
    }
}
