// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentResponsesFormatJsonSchemaJsonSchema } from "./AgentResponsesFormatJsonSchemaJsonSchema.js";

export const AgentResponsesFormatJsonSchema: core.serialization.ObjectSchema<
    serializers.AgentResponsesFormatJsonSchema.Raw,
    TrueFoundryGateway.AgentResponsesFormatJsonSchema
> = core.serialization.object({
    type: core.serialization.stringLiteral("json_schema"),
    json_schema: AgentResponsesFormatJsonSchemaJsonSchema,
});

export declare namespace AgentResponsesFormatJsonSchema {
    export interface Raw {
        type: "json_schema";
        json_schema: AgentResponsesFormatJsonSchemaJsonSchema.Raw;
    }
}
