// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentInfo: core.serialization.ObjectSchema<serializers.AgentInfo.Raw, TrueFoundryGateway.AgentInfo> =
    core.serialization.object({
        type: core.serialization.stringLiteral("dynamic"),
        name: core.serialization.string(),
        input: core.serialization.string(),
        model: core.serialization.string().optional(),
    });

export declare namespace AgentInfo {
    export interface Raw {
        type: "dynamic";
        name: string;
        input: string;
        model?: string | null;
    }
}
