// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentSpecUserMessageType: core.serialization.Schema<
    serializers.AgentSpecUserMessageType.Raw,
    TrueFoundryGateway.AgentSpecUserMessageType
> = core.serialization.enum_(["user.message"]);

export declare namespace AgentSpecUserMessageType {
    export type Raw = "user.message";
}
