// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentCompletionUsageCompletionTokensDetails: core.serialization.ObjectSchema<
    serializers.AgentCompletionUsageCompletionTokensDetails.Raw,
    TrueFoundryGateway.AgentCompletionUsageCompletionTokensDetails
> = core.serialization.object({
    reasoningTokens: core.serialization.property("reasoning_tokens", core.serialization.number().optional()),
});

export declare namespace AgentCompletionUsageCompletionTokensDetails {
    export interface Raw {
        reasoning_tokens?: number | null;
    }
}
