// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentExtendedDeltaToolCallToolInfo } from "./AgentExtendedDeltaToolCallToolInfo.js";
import { ChatCompletionChunkDeltaToolCall } from "./ChatCompletionChunkDeltaToolCall.js";

export const AgentExtendedDeltaToolCall: core.serialization.ObjectSchema<
    serializers.AgentExtendedDeltaToolCall.Raw,
    TrueFoundryGateway.AgentExtendedDeltaToolCall
> = core.serialization
    .object({
        tool_info: AgentExtendedDeltaToolCallToolInfo.optional(),
        provider_specific_fields: core.serialization
            .record(core.serialization.string(), core.serialization.unknown())
            .optional(),
    })
    .extend(ChatCompletionChunkDeltaToolCall);

export declare namespace AgentExtendedDeltaToolCall {
    export interface Raw extends ChatCompletionChunkDeltaToolCall.Raw {
        tool_info?: AgentExtendedDeltaToolCallToolInfo.Raw | null;
        provider_specific_fields?: Record<string, unknown> | null;
    }
}
