// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentInternalEnrichedAssistantMessageAudio } from "./AgentInternalEnrichedAssistantMessageAudio.js";
import { AgentInternalEnrichedAssistantMessageContent } from "./AgentInternalEnrichedAssistantMessageContent.js";
import { AgentInternalEnrichedAssistantMessageFunctionCall } from "./AgentInternalEnrichedAssistantMessageFunctionCall.js";
import { AgentInternalEnrichedAssistantMessageThinkingBlocksItem } from "./AgentInternalEnrichedAssistantMessageThinkingBlocksItem.js";
import { AgentInternalEnrichedToolCall } from "./AgentInternalEnrichedToolCall.js";

export const AgentInternalEnrichedAssistantMessage: core.serialization.ObjectSchema<
    serializers.AgentInternalEnrichedAssistantMessage.Raw,
    TrueFoundryGateway.AgentInternalEnrichedAssistantMessage
> = core.serialization.object({
    role: core.serialization.stringLiteral("assistant"),
    audio: AgentInternalEnrichedAssistantMessageAudio.optional(),
    content: AgentInternalEnrichedAssistantMessageContent.optional(),
    function_call: AgentInternalEnrichedAssistantMessageFunctionCall.optional(),
    name: core.serialization.string().optional(),
    refusal: core.serialization.string().optional(),
    thinking_blocks: core.serialization.list(AgentInternalEnrichedAssistantMessageThinkingBlocksItem).optional(),
    tool_calls: core.serialization.list(AgentInternalEnrichedToolCall).optional(),
});

export declare namespace AgentInternalEnrichedAssistantMessage {
    export interface Raw {
        role: "assistant";
        audio?: AgentInternalEnrichedAssistantMessageAudio.Raw | null;
        content?: AgentInternalEnrichedAssistantMessageContent.Raw | null;
        function_call?: AgentInternalEnrichedAssistantMessageFunctionCall.Raw | null;
        name?: string | null;
        refusal?: string | null;
        thinking_blocks?: AgentInternalEnrichedAssistantMessageThinkingBlocksItem.Raw[] | null;
        tool_calls?: AgentInternalEnrichedToolCall.Raw[] | null;
    }
}
