// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentConfigContextManagementCompaction: core.serialization.ObjectSchema<
    serializers.AgentConfigContextManagementCompaction.Raw,
    TrueFoundryGateway.AgentConfigContextManagementCompaction
> = core.serialization.object({
    enabled: core.serialization.boolean(),
    compaction_threshold_tokens: core.serialization.number(),
});

export declare namespace AgentConfigContextManagementCompaction {
    export interface Raw {
        enabled: boolean;
        compaction_threshold_tokens: number;
    }
}
