// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentMcpServerRequestRequireApprovalForToolsItem: core.serialization.Schema<
    serializers.AgentMcpServerRequestRequireApprovalForToolsItem.Raw,
    TrueFoundryGateway.AgentMcpServerRequestRequireApprovalForToolsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("@all"),
    core.serialization.stringLiteral("@write"),
    core.serialization.stringLiteral("@destructive"),
    core.serialization.string(),
]);

export declare namespace AgentMcpServerRequestRequireApprovalForToolsItem {
    export type Raw = "@all" | "@write" | "@destructive" | string;
}
