// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentRedactedThinkingBlock } from "./AgentRedactedThinkingBlock.js";
import { AgentThinkingBlock } from "./AgentThinkingBlock.js";

export const AgentInternalEnrichedAssistantMessageThinkingBlocksItem: core.serialization.Schema<
    serializers.AgentInternalEnrichedAssistantMessageThinkingBlocksItem.Raw,
    TrueFoundryGateway.AgentInternalEnrichedAssistantMessageThinkingBlocksItem
> = core.serialization.undiscriminatedUnion([AgentThinkingBlock, AgentRedactedThinkingBlock]);

export declare namespace AgentInternalEnrichedAssistantMessageThinkingBlocksItem {
    export type Raw = AgentThinkingBlock.Raw | AgentRedactedThinkingBlock.Raw;
}
