// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentInternalToolCallInfo } from "./AgentInternalToolCallInfo.js";
import { AgentRawToolCall } from "./AgentRawToolCall.js";

export const AgentInternalEnrichedToolCall: core.serialization.ObjectSchema<
    serializers.AgentInternalEnrichedToolCall.Raw,
    TrueFoundryGateway.AgentInternalEnrichedToolCall
> = core.serialization
    .object({
        toolInfo: core.serialization.property("tool_info", AgentInternalToolCallInfo),
    })
    .extend(AgentRawToolCall);

export declare namespace AgentInternalEnrichedToolCall {
    export interface Raw extends AgentRawToolCall.Raw {
        tool_info: AgentInternalToolCallInfo.Raw;
    }
}
