// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentMcpToolCallInfo: core.serialization.ObjectSchema<
    serializers.AgentMcpToolCallInfo.Raw,
    TrueFoundryGateway.AgentMcpToolCallInfo
> = core.serialization.object({
    type: core.serialization.stringLiteral("mcp"),
    server_id: core.serialization.string(),
    server_name: core.serialization.string(),
    name: core.serialization.string(),
});

export declare namespace AgentMcpToolCallInfo {
    export interface Raw {
        type: "mcp";
        server_id: string;
        server_name: string;
        name: string;
    }
}
