// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentConfigAskUserQuestions } from "./AgentConfigAskUserQuestions.js";
import { AgentConfigContextManagement } from "./AgentConfigContextManagement.js";
import { AgentConfigDynamicSubAgents } from "./AgentConfigDynamicSubAgents.js";
import { AgentConfigGenerativeUi } from "./AgentConfigGenerativeUi.js";
import { AgentConfigSandbox } from "./AgentConfigSandbox.js";

export const AgentConfig: core.serialization.ObjectSchema<serializers.AgentConfig.Raw, TrueFoundryGateway.AgentConfig> =
    core.serialization.object({
        iterationLimit: core.serialization.property("iteration_limit", core.serialization.number()),
        sandbox: AgentConfigSandbox.optional(),
        dynamicSubAgents: core.serialization.property("dynamic_sub_agents", AgentConfigDynamicSubAgents.optional()),
        contextManagement: core.serialization.property("context_management", AgentConfigContextManagement.optional()),
        generativeUi: core.serialization.property("generative_ui", AgentConfigGenerativeUi.optional()),
        askUserQuestions: core.serialization.property("ask_user_questions", AgentConfigAskUserQuestions.optional()),
    });

export declare namespace AgentConfig {
    export interface Raw {
        iteration_limit: number;
        sandbox?: AgentConfigSandbox.Raw | null;
        dynamic_sub_agents?: AgentConfigDynamicSubAgents.Raw | null;
        context_management?: AgentConfigContextManagement.Raw | null;
        generative_ui?: AgentConfigGenerativeUi.Raw | null;
        ask_user_questions?: AgentConfigAskUserQuestions.Raw | null;
    }
}
