// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ApprovalAllow } from "./ApprovalAllow.js";
import { ApprovalDeny } from "./ApprovalDeny.js";

export const ApprovalDecision: core.serialization.Schema<
    serializers.ApprovalDecision.Raw,
    TrueFoundryGateway.ApprovalDecision
> = core.serialization.undiscriminatedUnion([ApprovalAllow, ApprovalDeny]);

export declare namespace ApprovalDecision {
    export type Raw = ApprovalAllow.Raw | ApprovalDeny.Raw;
}
