// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BaseMcpAuthRequiredEvent: core.serialization.ObjectSchema<
    serializers.BaseMcpAuthRequiredEvent.Raw,
    TrueFoundryGateway.BaseMcpAuthRequiredEvent
> = core.serialization.object({
    id: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    threadId: core.serialization.property("thread_id", core.serialization.string().nullable()),
});

export declare namespace BaseMcpAuthRequiredEvent {
    export interface Raw {
        id: string;
        created_at: string;
        thread_id?: string | null;
    }
}
