// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CancelSessionResponse: core.serialization.ObjectSchema<
    serializers.CancelSessionResponse.Raw,
    TrueFoundryGateway.CancelSessionResponse
> = core.serialization.object({});

export declare namespace CancelSessionResponse {
    export type Raw = {};
}
