// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChatCompletionContentPartTextType: core.serialization.Schema<
    serializers.ChatCompletionContentPartTextType.Raw,
    TrueFoundryGateway.ChatCompletionContentPartTextType
> = core.serialization.enum_(["text"]);

export declare namespace ChatCompletionContentPartTextType {
    export type Raw = "text";
}
