// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChatCompletionContentPartText: core.serialization.ObjectSchema<
    serializers.ChatCompletionContentPartText.Raw,
    TrueFoundryGateway.ChatCompletionContentPartText
> = core.serialization.object({
    text: core.serialization.string(),
});

export declare namespace ChatCompletionContentPartText {
    export interface Raw {
        text: string;
    }
}
