// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChatCompletionContentPartImageImageUrlDetail: core.serialization.Schema<
    serializers.ChatCompletionContentPartImageImageUrlDetail.Raw,
    TrueFoundryGateway.ChatCompletionContentPartImageImageUrlDetail
> = core.serialization.enum_(["auto", "low", "high"]);

export declare namespace ChatCompletionContentPartImageImageUrlDetail {
    export type Raw = "auto" | "low" | "high";
}
