// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChatCompletionChunkDeltaToolCallType: core.serialization.Schema<
    serializers.ChatCompletionChunkDeltaToolCallType.Raw,
    TrueFoundryGateway.ChatCompletionChunkDeltaToolCallType
> = core.serialization.enum_(["function"]);

export declare namespace ChatCompletionChunkDeltaToolCallType {
    export type Raw = "function";
}
