// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ChatCompletionChunkDeltaToolCallFunction: core.serialization.ObjectSchema<
    serializers.ChatCompletionChunkDeltaToolCallFunction.Raw,
    TrueFoundryGateway.ChatCompletionChunkDeltaToolCallFunction
> = core.serialization.object({
    name: core.serialization.string().optional(),
    arguments: core.serialization.string().optional(),
});

export declare namespace ChatCompletionChunkDeltaToolCallFunction {
    export interface Raw {
        name?: string | null;
        arguments?: string | null;
    }
}
