// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ChatCompletionContentPartImageImageUrlDetail } from "./ChatCompletionContentPartImageImageUrlDetail.js";

export const ChatCompletionContentPartImageImageUrl: core.serialization.ObjectSchema<
    serializers.ChatCompletionContentPartImageImageUrl.Raw,
    TrueFoundryGateway.ChatCompletionContentPartImageImageUrl
> = core.serialization.object({
    url: core.serialization.string(),
    detail: ChatCompletionContentPartImageImageUrlDetail.optional(),
});

export declare namespace ChatCompletionContentPartImageImageUrl {
    export interface Raw {
        url: string;
        detail?: ChatCompletionContentPartImageImageUrlDetail.Raw | null;
    }
}
