// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ChatCompletionMessageToolCallFunction } from "./ChatCompletionMessageToolCallFunction.js";

export const ChatCompletionMessageToolCall: core.serialization.ObjectSchema<
    serializers.ChatCompletionMessageToolCall.Raw,
    TrueFoundryGateway.ChatCompletionMessageToolCall
> = core.serialization.object({
    id: core.serialization.string(),
    type: core.serialization.stringLiteral("function"),
    function: ChatCompletionMessageToolCallFunction,
});

export declare namespace ChatCompletionMessageToolCall {
    export interface Raw {
        id: string;
        type: "function";
        function: ChatCompletionMessageToolCallFunction.Raw;
    }
}
