// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ContextManagementConfigCompaction: core.serialization.ObjectSchema<
    serializers.ContextManagementConfigCompaction.Raw,
    TrueFoundryGateway.ContextManagementConfigCompaction
> = core.serialization.object({
    enabled: core.serialization.boolean().optional(),
    compactionThresholdTokens: core.serialization.property(
        "compaction_threshold_tokens",
        core.serialization.number().optional(),
    ),
});

export declare namespace ContextManagementConfigCompaction {
    export interface Raw {
        enabled?: boolean | null;
        compaction_threshold_tokens?: number | null;
    }
}
