// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CreatedBySubject: core.serialization.ObjectSchema<
    serializers.CreatedBySubject.Raw,
    TrueFoundryGateway.CreatedBySubject
> = core.serialization.object({
    subject_id: core.serialization.string(),
    subject_slug: core.serialization.string(),
    subject_type: core.serialization.string(),
    tenant_name: core.serialization.string(),
});

export declare namespace CreatedBySubject {
    export interface Raw {
        subject_id: string;
        subject_slug: string;
        subject_type: string;
        tenant_name: string;
    }
}
