// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DraftSessionType: core.serialization.Schema<
    serializers.DraftSessionType.Raw,
    TrueFoundryGateway.DraftSessionType
> = core.serialization.enum_(["session/draft"]);

export declare namespace DraftSessionType {
    export type Raw = "session/draft";
}
