// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentConfig } from "./AgentConfig.js";
import { AgentMcpServerRequest } from "./AgentMcpServerRequest.js";
import { AgentModelSpec } from "./AgentModelSpec.js";
import { AgentResponsesFormat } from "./AgentResponsesFormat.js";
import { AgentSkillMount } from "./AgentSkillMount.js";
import { DraftSessionAgentSpecMessagesItem } from "./DraftSessionAgentSpecMessagesItem.js";

export const DraftSessionAgentSpec: core.serialization.ObjectSchema<
    serializers.DraftSessionAgentSpec.Raw,
    TrueFoundryGateway.DraftSessionAgentSpec
> = core.serialization.object({
    model: AgentModelSpec,
    instructions: core.serialization.string().optional(),
    messages: core.serialization.list(DraftSessionAgentSpecMessagesItem).optional(),
    mcpServers: core.serialization.property("mcp_servers", core.serialization.list(AgentMcpServerRequest).optional()),
    responseFormat: core.serialization.property("response_format", AgentResponsesFormat.optional()),
    skills: core.serialization.list(AgentSkillMount).optional(),
    config: AgentConfig.optional(),
    variables: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
});

export declare namespace DraftSessionAgentSpec {
    export interface Raw {
        model: AgentModelSpec.Raw;
        instructions?: string | null;
        messages?: DraftSessionAgentSpecMessagesItem.Raw[] | null;
        mcp_servers?: AgentMcpServerRequest.Raw[] | null;
        response_format?: AgentResponsesFormat.Raw | null;
        skills?: AgentSkillMount.Raw[] | null;
        config?: AgentConfig.Raw | null;
        variables?: Record<string, string> | null;
    }
}
