// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DraftSessionAgentSpec } from "./DraftSessionAgentSpec.js";
import { SessionSubject } from "./SessionSubject.js";

export const DraftSession: core.serialization.ObjectSchema<
    serializers.DraftSession.Raw,
    TrueFoundryGateway.DraftSession
> = core.serialization.object({
    id: core.serialization.string(),
    agentSpec: core.serialization.property("agent_spec", DraftSessionAgentSpec),
    agentName: core.serialization.property("agent_name", core.serialization.string().optional()),
    title: core.serialization.string().optional(),
    createdBySubject: core.serialization.property("created_by_subject", SessionSubject),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    updatedAt: core.serialization.property("updated_at", core.serialization.string()),
});

export declare namespace DraftSession {
    export interface Raw {
        id: string;
        agent_spec: DraftSessionAgentSpec.Raw;
        agent_name?: string | null;
        title?: string | null;
        created_by_subject: SessionSubject.Raw;
        created_at: string;
        updated_at: string;
    }
}
