// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EnrichedToolCallToolInfo } from "./EnrichedToolCallToolInfo.js";
import { RawToolCall } from "./RawToolCall.js";

export const EnrichedToolCall: core.serialization.ObjectSchema<
    serializers.EnrichedToolCall.Raw,
    TrueFoundryGateway.EnrichedToolCall
> = core.serialization
    .object({
        toolInfo: core.serialization.property("tool_info", EnrichedToolCallToolInfo),
    })
    .extend(RawToolCall);

export declare namespace EnrichedToolCall {
    export interface Raw extends RawToolCall.Raw {
        tool_info: EnrichedToolCallToolInfo.Raw;
    }
}
