// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EventsTokenPaginationOrder: core.serialization.Schema<
    serializers.EventsTokenPaginationOrder.Raw,
    TrueFoundryGateway.EventsTokenPaginationOrder
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace EventsTokenPaginationOrder {
    export type Raw = "asc" | "desc";
}
