// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpToolCallInfo } from "./McpToolCallInfo.js";
import { TrueFoundrySystemToolCallInfo } from "./TrueFoundrySystemToolCallInfo.js";

export const ExtendedChunkDeltaToolCallToolInfo: core.serialization.Schema<
    serializers.ExtendedChunkDeltaToolCallToolInfo.Raw,
    TrueFoundryGateway.ExtendedChunkDeltaToolCallToolInfo
> = core.serialization.undiscriminatedUnion([TrueFoundrySystemToolCallInfo, McpToolCallInfo]);

export declare namespace ExtendedChunkDeltaToolCallToolInfo {
    export type Raw = TrueFoundrySystemToolCallInfo.Raw | McpToolCallInfo.Raw;
}
