// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FileUploadContentPartFile } from "./FileUploadContentPartFile.js";

export const FileUploadContentPart: core.serialization.ObjectSchema<
    serializers.FileUploadContentPart.Raw,
    TrueFoundryGateway.FileUploadContentPart
> = core.serialization.object({
    type: core.serialization.stringLiteral("file_upload"),
    file: FileUploadContentPartFile,
});

export declare namespace FileUploadContentPart {
    export interface Raw {
        type: "file_upload";
        file: FileUploadContentPartFile.Raw;
    }
}
