// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const FinishReason: core.serialization.Schema<serializers.FinishReason.Raw, TrueFoundryGateway.FinishReason> =
    core.serialization.enum_(["stop", "length", "tool_calls", "content_filter", "function_call"]);

export declare namespace FinishReason {
    export type Raw = "stop" | "length" | "tool_calls" | "content_filter" | "function_call";
}
