// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const InlineMcpServerEnableToolsItem: core.serialization.Schema<
    serializers.InlineMcpServerEnableToolsItem.Raw,
    TrueFoundryGateway.InlineMcpServerEnableToolsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("@all"),
    core.serialization.stringLiteral("@read-only"),
    core.serialization.string(),
]);

export declare namespace InlineMcpServerEnableToolsItem {
    export type Raw = "@all" | "@read-only" | string;
}
