// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LargeToolResponseConfig: core.serialization.ObjectSchema<
    serializers.LargeToolResponseConfig.Raw,
    TrueFoundryGateway.LargeToolResponseConfig
> = core.serialization.object({
    enabled: core.serialization.boolean().optional(),
});

export declare namespace LargeToolResponseConfig {
    export interface Raw {
        enabled?: boolean | null;
    }
}
