// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ListOwnedSessionsOrder: core.serialization.Schema<
    serializers.ListOwnedSessionsOrder.Raw,
    TrueFoundryGateway.ListOwnedSessionsOrder
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace ListOwnedSessionsOrder {
    export type Raw = "asc" | "desc";
}
