// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TokenPagination } from "./TokenPagination.js";
import { TurnEvent } from "./TurnEvent.js";

export const ListEventsResponse: core.serialization.ObjectSchema<
    serializers.ListEventsResponse.Raw,
    TrueFoundryGateway.ListEventsResponse
> = core.serialization.object({
    data: core.serialization.list(TurnEvent),
    pagination: TokenPagination,
});

export declare namespace ListEventsResponse {
    export interface Raw {
        data: TurnEvent.Raw[];
        pagination: TokenPagination.Raw;
    }
}
