// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SessionEventItem } from "./SessionEventItem.js";
import { TokenPagination } from "./TokenPagination.js";

export const ListSessionEventsResponse: core.serialization.ObjectSchema<
    serializers.ListSessionEventsResponse.Raw,
    TrueFoundryGateway.ListSessionEventsResponse
> = core.serialization.object({
    data: core.serialization.list(SessionEventItem),
    pagination: TokenPagination,
});

export declare namespace ListSessionEventsResponse {
    export interface Raw {
        data: SessionEventItem.Raw[];
        pagination: TokenPagination.Raw;
    }
}
