// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DraftSession } from "./DraftSession.js";
import { Session } from "./Session.js";

export const ListOwnedSessionsResponseDataItem: core.serialization.Schema<
    serializers.ListOwnedSessionsResponseDataItem.Raw,
    TrueFoundryGateway.ListOwnedSessionsResponseDataItem
> = core.serialization.undiscriminatedUnion([Session, DraftSession]);

export declare namespace ListOwnedSessionsResponseDataItem {
    export type Raw = Session.Raw | DraftSession.Raw;
}
