// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DraftSession } from "./DraftSession.js";
import { TokenPagination } from "./TokenPagination.js";

export const ListDraftSessionsResponse: core.serialization.ObjectSchema<
    serializers.ListDraftSessionsResponse.Raw,
    TrueFoundryGateway.ListDraftSessionsResponse
> = core.serialization.object({
    data: core.serialization.list(DraftSession),
    pagination: TokenPagination,
});

export declare namespace ListDraftSessionsResponse {
    export interface Raw {
        data: DraftSession.Raw[];
        pagination: TokenPagination.Raw;
    }
}
