// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpInitializationInfo } from "./McpInitializationInfo.js";

export const McpInitializeEvent: core.serialization.ObjectSchema<
    serializers.McpInitializeEvent.Raw,
    TrueFoundryGateway.McpInitializeEvent
> = core.serialization.object({
    type: core.serialization.stringLiteral("mcp.initialize"),
    id: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    threadId: core.serialization.property("thread_id", core.serialization.string()),
    content: core.serialization.list(McpInitializationInfo),
});

export declare namespace McpInitializeEvent {
    export interface Raw {
        type: "mcp.initialize";
        id: string;
        created_at: string;
        thread_id: string;
        content: McpInitializationInfo.Raw[];
    }
}
