// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { InlineMcpServer } from "./InlineMcpServer.js";
import { RegistryMcpServer } from "./RegistryMcpServer.js";

export const McpServer: core.serialization.Schema<serializers.McpServer.Raw, TrueFoundryGateway.McpServer> =
    core.serialization.undiscriminatedUnion([RegistryMcpServer, InlineMcpServer]);

export declare namespace McpServer {
    export type Raw = RegistryMcpServer.Raw | InlineMcpServer.Raw;
}
