// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { InlineMcpServer } from "./InlineMcpServer.js";
import { RegisteredMcpServer } from "./RegisteredMcpServer.js";

export const McpServer: core.serialization.Schema<serializers.McpServer.Raw, TrueFoundryGateway.McpServer> =
    core.serialization
        .union("type", {
            "truefoundry-mcp-registry": RegisteredMcpServer,
            inline: InlineMcpServer,
        })
        .transform<TrueFoundryGateway.McpServer>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace McpServer {
    export type Raw = McpServer.TruefoundryMcpRegistry | McpServer.Inline;

    export interface TruefoundryMcpRegistry extends RegisteredMcpServer.Raw {
        type: "truefoundry-mcp-registry";
    }

    export interface Inline extends InlineMcpServer.Raw {
        type: "inline";
    }
}
