// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const McpToolInfo: core.serialization.ObjectSchema<serializers.McpToolInfo.Raw, TrueFoundryGateway.McpToolInfo> =
    core.serialization.object({
        serverId: core.serialization.property("server_id", core.serialization.string()),
        serverName: core.serialization.property("server_name", core.serialization.string()),
        name: core.serialization.string(),
    });

export declare namespace McpToolInfo {
    export interface Raw {
        server_id: string;
        server_name: string;
        name: string;
    }
}
