// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ModelParamsReasoningEffort: core.serialization.Schema<
    serializers.ModelParamsReasoningEffort.Raw,
    TrueFoundryGateway.ModelParamsReasoningEffort
> = core.serialization.enum_(["none", "minimal", "low", "medium", "high"]);

export declare namespace ModelParamsReasoningEffort {
    export type Raw = "none" | "minimal" | "low" | "medium" | "high";
}
