// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentEnrichedToolCall } from "./AgentEnrichedToolCall.js";
import { AgentFinishReason } from "./AgentFinishReason.js";
import { ModelMessageEventAudio } from "./ModelMessageEventAudio.js";
import { ModelMessageEventContent } from "./ModelMessageEventContent.js";
import { ModelMessageEventFunctionCall } from "./ModelMessageEventFunctionCall.js";
import { ModelMessageEventThinkingBlocksItem } from "./ModelMessageEventThinkingBlocksItem.js";
import { ModelMessageEventUsage } from "./ModelMessageEventUsage.js";

export const ModelMessageEvent: core.serialization.ObjectSchema<
    serializers.ModelMessageEvent.Raw,
    TrueFoundryGateway.ModelMessageEvent
> = core.serialization.object({
    audio: ModelMessageEventAudio.optional(),
    content: ModelMessageEventContent.optional(),
    function_call: ModelMessageEventFunctionCall.optional(),
    name: core.serialization.string().optional(),
    refusal: core.serialization.string().optional(),
    thinking_blocks: core.serialization.list(ModelMessageEventThinkingBlocksItem).optional(),
    tool_calls: core.serialization.list(AgentEnrichedToolCall).optional(),
    type: core.serialization.stringLiteral("model.message"),
    id: core.serialization.string(),
    thread_id: core.serialization.string(),
    finish_reason: AgentFinishReason.optional(),
    created_at: core.serialization.string(),
    usage: ModelMessageEventUsage.optional(),
});

export declare namespace ModelMessageEvent {
    export interface Raw {
        audio?: ModelMessageEventAudio.Raw | null;
        content?: ModelMessageEventContent.Raw | null;
        function_call?: ModelMessageEventFunctionCall.Raw | null;
        name?: string | null;
        refusal?: string | null;
        thinking_blocks?: ModelMessageEventThinkingBlocksItem.Raw[] | null;
        tool_calls?: AgentEnrichedToolCall.Raw[] | null;
        type: "model.message";
        id: string;
        thread_id: string;
        finish_reason?: AgentFinishReason.Raw | null;
        created_at: string;
        usage?: ModelMessageEventUsage.Raw | null;
    }
}
