// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RedactedThinkingBlock } from "./RedactedThinkingBlock.js";
import { ThinkingBlock } from "./ThinkingBlock.js";

export const ModelMessageDeltaEventThinkingBlocksItem: core.serialization.Schema<
    serializers.ModelMessageDeltaEventThinkingBlocksItem.Raw,
    TrueFoundryGateway.ModelMessageDeltaEventThinkingBlocksItem
> = core.serialization.undiscriminatedUnion([ThinkingBlock, RedactedThinkingBlock]);

export declare namespace ModelMessageDeltaEventThinkingBlocksItem {
    export type Raw = ThinkingBlock.Raw | RedactedThinkingBlock.Raw;
}
