// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ModelParamsCacheControl: core.serialization.ObjectSchema<
    serializers.ModelParamsCacheControl.Raw,
    TrueFoundryGateway.ModelParamsCacheControl
> = core.serialization.object({
    type: core.serialization.string(),
});

export declare namespace ModelParamsCacheControl {
    export interface Raw {
        type: string;
    }
}
