// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ModelMessageEventUsageInputTokensBreakdown: core.serialization.ObjectSchema<
    serializers.ModelMessageEventUsageInputTokensBreakdown.Raw,
    TrueFoundryGateway.ModelMessageEventUsageInputTokensBreakdown
> = core.serialization.object({
    harness: core.serialization.number(),
    skills: core.serialization.number(),
    instructions: core.serialization.number(),
    toolDefinitions: core.serialization.property("tool_definitions", core.serialization.number()),
    messages: core.serialization.number(),
});

export declare namespace ModelMessageEventUsageInputTokensBreakdown {
    export interface Raw {
        harness: number;
        skills: number;
        instructions: number;
        tool_definitions: number;
        messages: number;
    }
}
