// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ModelParams } from "./ModelParams.js";

export const Model: core.serialization.ObjectSchema<serializers.Model.Raw, TrueFoundryGateway.Model> =
    core.serialization.object({
        name: core.serialization.string(),
        params: ModelParams.optional(),
    });

export declare namespace Model {
    export interface Raw {
        name: string;
        params?: ModelParams.Raw | null;
    }
}
