// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ExtendedChunkDeltaToolCall } from "./ExtendedChunkDeltaToolCall.js";
import { FinishReason } from "./FinishReason.js";
import { ModelMessageUsage } from "./ModelMessageUsage.js";

export const ModelMessageDeltaEvent: core.serialization.ObjectSchema<
    serializers.ModelMessageDeltaEvent.Raw,
    TrueFoundryGateway.ModelMessageDeltaEvent
> = core.serialization.object({
    content: core.serialization.string().optional(),
    refusal: core.serialization.string().optional(),
    toolCalls: core.serialization.property(
        "tool_calls",
        core.serialization.list(ExtendedChunkDeltaToolCall).optional(),
    ),
    reasoningContent: core.serialization.property("reasoning_content", core.serialization.string().optional()),
    type: core.serialization.stringLiteral("model.message.delta"),
    id: core.serialization.string(),
    threadId: core.serialization.property("thread_id", core.serialization.string()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    finishReason: core.serialization.property("finish_reason", FinishReason.optional()),
    usage: ModelMessageUsage.optional(),
});

export declare namespace ModelMessageDeltaEvent {
    export interface Raw {
        content?: string | null;
        refusal?: string | null;
        tool_calls?: ExtendedChunkDeltaToolCall.Raw[] | null;
        reasoning_content?: string | null;
        type: "model.message.delta";
        id: string;
        thread_id: string;
        created_at?: string | null;
        finish_reason?: FinishReason.Raw | null;
        usage?: ModelMessageUsage.Raw | null;
    }
}
