// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PreviousTurnIdInput: core.serialization.Schema<
    serializers.PreviousTurnIdInput.Raw,
    TrueFoundryGateway.PreviousTurnIdInput
> = core.serialization.undiscriminatedUnion([core.serialization.stringLiteral("auto"), core.serialization.string()]);

export declare namespace PreviousTurnIdInput {
    export type Raw = "auto" | string;
}
