// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PreviousTurnIdInputZero: core.serialization.Schema<
    serializers.PreviousTurnIdInputZero.Raw,
    TrueFoundryGateway.PreviousTurnIdInputZero
> = core.serialization.enum_(["auto"]);

export declare namespace PreviousTurnIdInputZero {
    export type Raw = "auto";
}
