// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const RegisteredSkillMount: core.serialization.ObjectSchema<
    serializers.RegisteredSkillMount.Raw,
    TrueFoundryGateway.RegisteredSkillMount
> = core.serialization.object({
    type: core.serialization.stringLiteral("truefoundry-skills-registry"),
    fqn: core.serialization.string(),
    preload: core.serialization.boolean().optional(),
});

export declare namespace RegisteredSkillMount {
    export interface Raw {
        type: "truefoundry-skills-registry";
        fqn: string;
        preload?: boolean | null;
    }
}
