// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const RequestErrorResponseError: core.serialization.ObjectSchema<
    serializers.RequestErrorResponseError.Raw,
    TrueFoundryGateway.RequestErrorResponseError
> = core.serialization.object({
    message: core.serialization.string(),
    type: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    param: core.serialization.string().optional(),
});

export declare namespace RequestErrorResponseError {
    export interface Raw {
        message: string;
        type?: string | null;
        code?: string | null;
        param?: string | null;
    }
}
