// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RequireApprovalToolsSelectorTag } from "./RequireApprovalToolsSelectorTag.js";

export const RequireApprovalToolSelectorItem: core.serialization.Schema<
    serializers.RequireApprovalToolSelectorItem.Raw,
    TrueFoundryGateway.RequireApprovalToolSelectorItem
> = core.serialization.undiscriminatedUnion([RequireApprovalToolsSelectorTag, core.serialization.string()]);

export declare namespace RequireApprovalToolSelectorItem {
    export type Raw = RequireApprovalToolsSelectorTag.Raw | string;
}
