// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ResponseFormatOneType } from "./ResponseFormatOneType.js";

export const ResponseFormatOne: core.serialization.ObjectSchema<
    serializers.ResponseFormatOne.Raw,
    TrueFoundryGateway.ResponseFormatOne
> = core.serialization.object({
    type: ResponseFormatOneType,
});

export declare namespace ResponseFormatOne {
    export interface Raw {
        type: ResponseFormatOneType.Raw;
    }
}
