// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ResponseFormatOneType: core.serialization.Schema<
    serializers.ResponseFormatOneType.Raw,
    TrueFoundryGateway.ResponseFormatOneType
> = core.serialization.enum_(["json_object"]);

export declare namespace ResponseFormatOneType {
    export type Raw = "json_object";
}
