// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ResponseFormatJsonSchemaJsonSchema } from "./ResponseFormatJsonSchemaJsonSchema.js";

export const ResponseFormatJsonSchema: core.serialization.ObjectSchema<
    serializers.ResponseFormatJsonSchema.Raw,
    TrueFoundryGateway.ResponseFormatJsonSchema
> = core.serialization.object({
    jsonSchema: core.serialization.property("json_schema", ResponseFormatJsonSchemaJsonSchema),
});

export declare namespace ResponseFormatJsonSchema {
    export interface Raw {
        json_schema: ResponseFormatJsonSchemaJsonSchema.Raw;
    }
}
