// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const RuntimeConfigGenerativeUi: core.serialization.ObjectSchema<
    serializers.RuntimeConfigGenerativeUi.Raw,
    TrueFoundryGateway.RuntimeConfigGenerativeUi
> = core.serialization.object({
    enabled: core.serialization.boolean(),
});

export declare namespace RuntimeConfigGenerativeUi {
    export interface Raw {
        enabled: boolean;
    }
}
