// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const RuntimeConfigContextManagementCompaction: core.serialization.ObjectSchema<
    serializers.RuntimeConfigContextManagementCompaction.Raw,
    TrueFoundryGateway.RuntimeConfigContextManagementCompaction
> = core.serialization.object({
    enabled: core.serialization.boolean(),
    compactionThresholdTokens: core.serialization.property("compaction_threshold_tokens", core.serialization.number()),
});

export declare namespace RuntimeConfigContextManagementCompaction {
    export interface Raw {
        enabled: boolean;
        compaction_threshold_tokens: number;
    }
}
