// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SandboxNetworkPolicyAuthInjectItemAuthDataType: core.serialization.Schema<
    serializers.SandboxNetworkPolicyAuthInjectItemAuthDataType.Raw,
    TrueFoundryGateway.SandboxNetworkPolicyAuthInjectItemAuthDataType
> = core.serialization.enum_(["basic"]);

export declare namespace SandboxNetworkPolicyAuthInjectItemAuthDataType {
    export type Raw = "basic";
}
