// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SandboxNetworkPolicy } from "./SandboxNetworkPolicy.js";

export const SandboxConfig: core.serialization.ObjectSchema<
    serializers.SandboxConfig.Raw,
    TrueFoundryGateway.SandboxConfig
> = core.serialization.object({
    enabled: core.serialization.boolean(),
    fileDownloads: core.serialization.property("file_downloads", core.serialization.boolean().optional()),
    networkPolicy: core.serialization.property("network_policy", SandboxNetworkPolicy.optional()),
});

export declare namespace SandboxConfig {
    export interface Raw {
        enabled: boolean;
        file_downloads?: boolean | null;
        network_policy?: SandboxNetworkPolicy.Raw | null;
    }
}
