// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SandboxNetworkPolicyAuthInjectItemMatch: core.serialization.ObjectSchema<
    serializers.SandboxNetworkPolicyAuthInjectItemMatch.Raw,
    TrueFoundryGateway.SandboxNetworkPolicyAuthInjectItemMatch
> = core.serialization.object({
    hosts: core.serialization.list(core.serialization.string()),
});

export declare namespace SandboxNetworkPolicyAuthInjectItemMatch {
    export interface Raw {
        hosts: string[];
    }
}
