// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SearchSessionsResponseDataItem } from "./SearchSessionsResponseDataItem.js";
import { TokenPagination } from "./TokenPagination.js";

export const SearchSessionsResponse: core.serialization.ObjectSchema<
    serializers.SearchSessionsResponse.Raw,
    TrueFoundryGateway.SearchSessionsResponse
> = core.serialization.object({
    data: core.serialization.list(SearchSessionsResponseDataItem),
    pagination: TokenPagination,
});

export declare namespace SearchSessionsResponse {
    export interface Raw {
        data: SearchSessionsResponseDataItem.Raw[];
        pagination: TokenPagination.Raw;
    }
}
