// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SessionSubject: core.serialization.ObjectSchema<
    serializers.SessionSubject.Raw,
    TrueFoundryGateway.SessionSubject
> = core.serialization.object({
    subjectId: core.serialization.property("subject_id", core.serialization.string()),
    subjectType: core.serialization.property("subject_type", core.serialization.string()),
    subjectSlug: core.serialization.property("subject_slug", core.serialization.string().optional()),
    subjectDisplayName: core.serialization.property("subject_display_name", core.serialization.string().optional()),
    subjectPatName: core.serialization.property("subject_pat_name", core.serialization.string().optional()),
    subjectControllerName: core.serialization.property(
        "subject_controller_name",
        core.serialization.string().optional(),
    ),
    subjectExternalIdentitySlug: core.serialization.property(
        "subject_external_identity_slug",
        core.serialization.string().optional(),
    ),
});

export declare namespace SessionSubject {
    export interface Raw {
        subject_id: string;
        subject_type: string;
        subject_slug?: string | null;
        subject_display_name?: string | null;
        subject_pat_name?: string | null;
        subject_controller_name?: string | null;
        subject_external_identity_slug?: string | null;
    }
}
