// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SessionSubject } from "./SessionSubject.js";

export const Session: core.serialization.ObjectSchema<serializers.Session.Raw, TrueFoundryGateway.Session> =
    core.serialization.object({
        id: core.serialization.string(),
        agent_name: core.serialization.string(),
        title: core.serialization.string().optional(),
        created_by_subject: SessionSubject,
        created_at: core.serialization.string(),
        updated_at: core.serialization.string(),
    });

export declare namespace Session {
    export interface Raw {
        id: string;
        agent_name: string;
        title?: string | null;
        created_by_subject: SessionSubject.Raw;
        created_at: string;
        updated_at: string;
    }
}
