// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SessionType: core.serialization.Schema<serializers.SessionType.Raw, TrueFoundryGateway.SessionType> =
    core.serialization.enum_(["session"]);

export declare namespace SessionType {
    export type Raw = "session";
}
