// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SessionSubject: core.serialization.ObjectSchema<
    serializers.SessionSubject.Raw,
    TrueFoundryGateway.SessionSubject
> = core.serialization.object({
    subject_id: core.serialization.string(),
    subject_type: core.serialization.string(),
    subject_slug: core.serialization.string().optional(),
    subject_display_name: core.serialization.string().optional(),
    subject_pat_name: core.serialization.string().optional(),
    subject_controller_name: core.serialization.string().optional(),
    subject_external_identity_slug: core.serialization.string().optional(),
});

export declare namespace SessionSubject {
    export interface Raw {
        subject_id: string;
        subject_type: string;
        subject_slug?: string | null;
        subject_display_name?: string | null;
        subject_pat_name?: string | null;
        subject_controller_name?: string | null;
        subject_external_identity_slug?: string | null;
    }
}
