// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Skill: core.serialization.ObjectSchema<serializers.Skill.Raw, TrueFoundryGateway.Skill> =
    core.serialization.object({
        fqn: core.serialization.string(),
        preload: core.serialization.boolean().optional(),
    });

export declare namespace Skill {
    export interface Raw {
        fqn: string;
        preload?: boolean | null;
    }
}
