// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TextContentPart: core.serialization.ObjectSchema<
    serializers.TextContentPart.Raw,
    TrueFoundryGateway.TextContentPart
> = core.serialization.object({
    type: core.serialization.stringLiteral("text"),
    text: core.serialization.string(),
});

export declare namespace TextContentPart {
    export interface Raw {
        type: "text";
        text: string;
    }
}
