// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ThreadStateDone } from "./ThreadStateDone.js";
import { ThreadStateError } from "./ThreadStateError.js";

export const ThreadState: core.serialization.Schema<serializers.ThreadState.Raw, TrueFoundryGateway.ThreadState> =
    core.serialization
        .union("status", {
            done: ThreadStateDone,
            error: ThreadStateError,
        })
        .transform<TrueFoundryGateway.ThreadState>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace ThreadState {
    export type Raw = ThreadState.Done | ThreadState.Error;

    export interface Done extends ThreadStateDone.Raw {
        status: "done";
    }

    export interface Error extends ThreadStateError.Raw {
        status: "error";
    }
}
