// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ModelMessageEvent } from "./ModelMessageEvent.js";

export const ThreadStateError: core.serialization.ObjectSchema<
    serializers.ThreadStateError.Raw,
    TrueFoundryGateway.ThreadStateError
> = core.serialization.object({
    error: core.serialization.string(),
    output: ModelMessageEvent.optional(),
});

export declare namespace ThreadStateError {
    export interface Raw {
        error: string;
        output?: ModelMessageEvent.Raw | null;
    }
}
