// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentParent } from "./AgentParent.js";
import { ModelMessageEvent } from "./ModelMessageEvent.js";

export const ThreadDoneCompleted: core.serialization.ObjectSchema<
    serializers.ThreadDoneCompleted.Raw,
    TrueFoundryGateway.ThreadDoneCompleted
> = core.serialization.object({
    type: core.serialization.stringLiteral("thread.done"),
    id: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    output: ModelMessageEvent,
    parent: AgentParent.optional(),
    status: core.serialization.stringLiteral("done"),
    threadId: core.serialization.property("thread_id", core.serialization.string()),
    title: core.serialization.string(),
});

export declare namespace ThreadDoneCompleted {
    export interface Raw {
        type: "thread.done";
        id: string;
        created_at: string;
        output: ModelMessageEvent.Raw;
        parent?: AgentParent.Raw | null;
        status: "done";
        thread_id: string;
        title: string;
    }
}
