// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentInfo } from "./AgentInfo.js";
import { AgentParent } from "./AgentParent.js";

export const ThreadCreatedEvent: core.serialization.ObjectSchema<
    serializers.ThreadCreatedEvent.Raw,
    TrueFoundryGateway.ThreadCreatedEvent
> = core.serialization.object({
    id: core.serialization.string(),
    agentInfo: core.serialization.property("agent_info", AgentInfo),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    parent: AgentParent,
    threadId: core.serialization.property("thread_id", core.serialization.string()),
    title: core.serialization.string(),
});

export declare namespace ThreadCreatedEvent {
    export interface Raw {
        id: string;
        agent_info: AgentInfo.Raw;
        created_at: string;
        parent: AgentParent.Raw;
        thread_id: string;
        title: string;
    }
}
