// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpToolInfo } from "./McpToolInfo.js";
import { TrueFoundrySystemToolInfo } from "./TrueFoundrySystemToolInfo.js";

export const ToolInfo: core.serialization.Schema<serializers.ToolInfo.Raw, TrueFoundryGateway.ToolInfo> =
    core.serialization.undiscriminatedUnion([TrueFoundrySystemToolInfo, McpToolInfo]);

export declare namespace ToolInfo {
    export type Raw = TrueFoundrySystemToolInfo.Raw | McpToolInfo.Raw;
}
