// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { RawToolCall } from "./RawToolCall.js";
import { ToolInfo } from "./ToolInfo.js";

export const ToolCall: core.serialization.ObjectSchema<serializers.ToolCall.Raw, TrueFoundryGateway.ToolCall> =
    core.serialization
        .object({
            toolInfo: core.serialization.property("tool_info", ToolInfo),
        })
        .extend(RawToolCall);

export declare namespace ToolCall {
    export interface Raw extends RawToolCall.Raw {
        tool_info: ToolInfo.Raw;
    }
}
