// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentToolCallRef } from "./AgentToolCallRef.js";

export const ToolResponseRequiredEvent: core.serialization.ObjectSchema<
    serializers.ToolResponseRequiredEvent.Raw,
    TrueFoundryGateway.ToolResponseRequiredEvent
> = core.serialization.object({
    type: core.serialization.stringLiteral("tool.response_required"),
    id: core.serialization.string(),
    created_at: core.serialization.string(),
    thread_id: core.serialization.string(),
    tool_calls: core.serialization.list(AgentToolCallRef),
});

export declare namespace ToolResponseRequiredEvent {
    export interface Raw {
        type: "tool.response_required";
        id: string;
        created_at: string;
        thread_id: string;
        tool_calls: AgentToolCallRef.Raw[];
    }
}
