// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TurnEventAudio: core.serialization.ObjectSchema<
    serializers.TurnEventAudio.Raw,
    TrueFoundryGateway.TurnEventAudio
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace TurnEventAudio {
    export interface Raw {
        id: string;
    }
}
