// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Subject } from "./Subject.js";
import { TurnInputItem } from "./TurnInputItem.js";
import { TurnState } from "./TurnState.js";

export const Turn: core.serialization.ObjectSchema<serializers.Turn.Raw, TrueFoundryGateway.Turn> =
    core.serialization.object({
        id: core.serialization.string(),
        sessionId: core.serialization.property("session_id", core.serialization.string()),
        previousTurnId: core.serialization.property("previous_turn_id", core.serialization.string().optional()),
        input: core.serialization.list(TurnInputItem),
        state: TurnState,
        createdBySubject: core.serialization.property("created_by_subject", Subject),
        createdAt: core.serialization.property("created_at", core.serialization.string()),
    });

export declare namespace Turn {
    export interface Raw {
        id: string;
        session_id: string;
        previous_turn_id?: string | null;
        input: TurnInputItem.Raw[];
        state: TurnState.Raw;
        created_by_subject: Subject.Raw;
        created_at: string;
    }
}
