// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ApprovalDecision } from "./ApprovalDecision.js";

export const TurnStreamingOutputEventContextItemApproval: core.serialization.ObjectSchema<
    serializers.TurnStreamingOutputEventContextItemApproval.Raw,
    TrueFoundryGateway.TurnStreamingOutputEventContextItemApproval
> = core.serialization.object({
    type: core.serialization.stringLiteral("user.tool_approval"),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
    approval: ApprovalDecision,
});

export declare namespace TurnStreamingOutputEventContextItemApproval {
    export interface Raw {
        type: "user.tool_approval";
        tool_call_id: string;
        approval: ApprovalDecision.Raw;
    }
}
