// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnStateCancelledReason } from "./TurnStateCancelledReason.js";

export const TurnStateCancelled: core.serialization.ObjectSchema<
    serializers.TurnStateCancelled.Raw,
    TrueFoundryGateway.TurnStateCancelled
> = core.serialization.object({
    status: core.serialization.stringLiteral("cancelled"),
    reason: TurnStateCancelledReason,
    completedAt: core.serialization.property("completed_at", core.serialization.string()),
});

export declare namespace TurnStateCancelled {
    export interface Raw {
        status: "cancelled";
        reason: TurnStateCancelledReason.Raw;
        completed_at: string;
    }
}
