// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ChatCompletionContentPartRefusal } from "./ChatCompletionContentPartRefusal.js";
import { ChatCompletionContentPartText } from "./ChatCompletionContentPartText.js";

export const TurnStateDoneOutputContentOneItem: core.serialization.Schema<
    serializers.TurnStateDoneOutputContentOneItem.Raw,
    TrueFoundryGateway.TurnStateDoneOutputContentOneItem
> = core.serialization.undiscriminatedUnion([ChatCompletionContentPartText, ChatCompletionContentPartRefusal]);

export declare namespace TurnStateDoneOutputContentOneItem {
    export type Raw = ChatCompletionContentPartText.Raw | ChatCompletionContentPartRefusal.Raw;
}
