// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TurnStateRunningStatus: core.serialization.Schema<
    serializers.TurnStateRunningStatus.Raw,
    TrueFoundryGateway.TurnStateRunningStatus
> = core.serialization.enum_(["running"]);

export declare namespace TurnStateRunningStatus {
    export type Raw = "running";
}
