// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ActionRequiredEvent } from "./ActionRequiredEvent.js";
import { TurnStateDoneOutput } from "./TurnStateDoneOutput.js";

export const TurnStateDone: core.serialization.ObjectSchema<
    serializers.TurnStateDone.Raw,
    TrueFoundryGateway.TurnStateDone
> = core.serialization.object({
    status: core.serialization.stringLiteral("done"),
    output: TurnStateDoneOutput.optionalNullable(),
    requiredActions: core.serialization.property("required_actions", core.serialization.list(ActionRequiredEvent)),
    completedAt: core.serialization.property("completed_at", core.serialization.string()),
});

export declare namespace TurnStateDone {
    export interface Raw {
        status: "done";
        output?: (TurnStateDoneOutput.Raw | null | undefined) | null;
        required_actions: ActionRequiredEvent.Raw[];
        completed_at: string;
    }
}
