// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { McpAuthRequiredEvent } from "./McpAuthRequiredEvent.js";
import { McpInitializeEvent } from "./McpInitializeEvent.js";
import { ModelMessageEvent } from "./ModelMessageEvent.js";
import { SandboxCreatedEvent } from "./SandboxCreatedEvent.js";
import { ThreadCreatedEvent } from "./ThreadCreatedEvent.js";
import { ThreadDoneEvent } from "./ThreadDoneEvent.js";
import { ToolApprovalRequiredEvent } from "./ToolApprovalRequiredEvent.js";
import { ToolResponseEvent } from "./ToolResponseEvent.js";
import { ToolResponseRequiredEvent } from "./ToolResponseRequiredEvent.js";

export const TurnEvent: core.serialization.Schema<serializers.TurnEvent.Raw, TrueFoundryGateway.TurnEvent> =
    core.serialization.undiscriminatedUnion([
        ModelMessageEvent,
        ToolResponseEvent,
        ThreadCreatedEvent,
        ThreadDoneEvent,
        McpAuthRequiredEvent,
        McpInitializeEvent,
        SandboxCreatedEvent,
        ToolApprovalRequiredEvent,
        ToolResponseRequiredEvent,
    ]);

export declare namespace TurnEvent {
    export type Raw =
        | ModelMessageEvent.Raw
        | ToolResponseEvent.Raw
        | ThreadCreatedEvent.Raw
        | ThreadDoneEvent.Raw
        | McpAuthRequiredEvent.Raw
        | McpInitializeEvent.Raw
        | SandboxCreatedEvent.Raw
        | ToolApprovalRequiredEvent.Raw
        | ToolResponseRequiredEvent.Raw;
}
