// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnInputItem } from "./TurnInputItem.js";
import { TurnState } from "./TurnState.js";

export const Turn: core.serialization.ObjectSchema<serializers.Turn.Raw, TrueFoundryGateway.Turn> =
    core.serialization.object({
        id: core.serialization.string(),
        session_id: core.serialization.string(),
        first_turn_id: core.serialization.string(),
        previous_turn_id: core.serialization.string().optional(),
        state: TurnState,
        input: core.serialization.list(TurnInputItem),
        created_at: core.serialization.string(),
        updated_at: core.serialization.string(),
    });

export declare namespace Turn {
    export interface Raw {
        id: string;
        session_id: string;
        first_turn_id: string;
        previous_turn_id?: string | null;
        state: TurnState.Raw;
        input: TurnInputItem.Raw[];
        created_at: string;
        updated_at: string;
    }
}
