// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnOutputEventContentOneItem } from "./TurnOutputEventContentOneItem.js";

export const TurnOutputEventContent: core.serialization.Schema<
    serializers.TurnOutputEventContent.Raw,
    TrueFoundryGateway.TurnOutputEventContent
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.list(TurnOutputEventContentOneItem),
]);

export declare namespace TurnOutputEventContent {
    export type Raw = string | TurnOutputEventContentOneItem.Raw[];
}
