// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentCompletionUsage } from "./AgentCompletionUsage.js";
import { AgentFinishReason } from "./AgentFinishReason.js";
import { AgentInfo } from "./AgentInfo.js";
import { AgentMcpInitializationInfo } from "./AgentMcpInitializationInfo.js";
import { AgentMcpServerAuthInfo } from "./AgentMcpServerAuthInfo.js";
import { AgentParent } from "./AgentParent.js";
import { AgentToolCallRef } from "./AgentToolCallRef.js";
import { CreatedBySubject } from "./CreatedBySubject.js";
import { TurnStreamingOutputEventAudio } from "./TurnStreamingOutputEventAudio.js";
import { TurnStreamingOutputEventContextItem } from "./TurnStreamingOutputEventContextItem.js";
import { TurnStreamingOutputEventFunctionCall } from "./TurnStreamingOutputEventFunctionCall.js";
import { TurnStreamingOutputEventThinkingBlocksItem } from "./TurnStreamingOutputEventThinkingBlocksItem.js";
import { TurnStreamingOutputEventUsage } from "./TurnStreamingOutputEventUsage.js";

export const TurnStreamingOutputEvent: core.serialization.ObjectSchema<
    serializers.TurnStreamingOutputEvent.Raw,
    TrueFoundryGateway.TurnStreamingOutputEvent
> = core.serialization.object({
    audio: TurnStreamingOutputEventAudio.optional(),
    content: core.serialization.list(AgentMcpInitializationInfo).optional(),
    function_call: TurnStreamingOutputEventFunctionCall.optional(),
    name: core.serialization.string().optional(),
    refusal: core.serialization.string().optional(),
    thinking_blocks: core.serialization.list(TurnStreamingOutputEventThinkingBlocksItem).optional(),
    tool_calls: core.serialization.list(AgentToolCallRef).optional(),
    type: core.serialization.stringLiteral("turn.created").optional(),
    id: core.serialization.string().optional(),
    thread_id: core.serialization.string().optional(),
    finish_reason: AgentFinishReason.optional(),
    created_at: core.serialization.string().optional(),
    usage: TurnStreamingOutputEventUsage.optional(),
    reasoning_content: core.serialization.string().optional(),
    tool_call_id: core.serialization.string().optional(),
    agent_info: AgentInfo.optional(),
    parent: AgentParent.optional(),
    title: core.serialization.string().optional(),
    reason: core.serialization.stringLiteral("compaction").optional(),
    context: core.serialization.list(TurnStreamingOutputEventContextItem).optional(),
    current_context_usage: AgentCompletionUsage.optional(),
    compaction_llm_usage: AgentCompletionUsage.optional(),
    servers: core.serialization.list(AgentMcpServerAuthInfo).optional(),
    sandbox_id: core.serialization.string().optional(),
    turn_id: core.serialization.string().optional(),
    previous_turn_id: core.serialization.string().optional(),
    created_by: CreatedBySubject.optional(),
    sequence_number: core.serialization.number(),
});

export declare namespace TurnStreamingOutputEvent {
    export interface Raw {
        audio?: TurnStreamingOutputEventAudio.Raw | null;
        content?: AgentMcpInitializationInfo.Raw[] | null;
        function_call?: TurnStreamingOutputEventFunctionCall.Raw | null;
        name?: string | null;
        refusal?: string | null;
        thinking_blocks?: TurnStreamingOutputEventThinkingBlocksItem.Raw[] | null;
        tool_calls?: AgentToolCallRef.Raw[] | null;
        type?: "turn.created" | null;
        id?: string | null;
        thread_id?: string | null;
        finish_reason?: AgentFinishReason.Raw | null;
        created_at?: string | null;
        usage?: TurnStreamingOutputEventUsage.Raw | null;
        reasoning_content?: string | null;
        tool_call_id?: string | null;
        agent_info?: AgentInfo.Raw | null;
        parent?: AgentParent.Raw | null;
        title?: string | null;
        reason?: "compaction" | null;
        context?: TurnStreamingOutputEventContextItem.Raw[] | null;
        current_context_usage?: AgentCompletionUsage.Raw | null;
        compaction_llm_usage?: AgentCompletionUsage.Raw | null;
        servers?: AgentMcpServerAuthInfo.Raw[] | null;
        sandbox_id?: string | null;
        turn_id?: string | null;
        previous_turn_id?: string | null;
        created_by?: CreatedBySubject.Raw | null;
        sequence_number: number;
    }
}
