// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnStreamingOutputEventUsageInputTokensBreakdown } from "./TurnStreamingOutputEventUsageInputTokensBreakdown.js";

export const TurnStreamingOutputEventUsage: core.serialization.ObjectSchema<
    serializers.TurnStreamingOutputEventUsage.Raw,
    TrueFoundryGateway.TurnStreamingOutputEventUsage
> = core.serialization.object({
    input_tokens: core.serialization.number(),
    output_tokens: core.serialization.number(),
    cache_read_tokens: core.serialization.number().optional(),
    cache_write_tokens: core.serialization.number().optional(),
    input_tokens_breakdown: TurnStreamingOutputEventUsageInputTokensBreakdown,
});

export declare namespace TurnStreamingOutputEventUsage {
    export interface Raw {
        input_tokens: number;
        output_tokens: number;
        cache_read_tokens?: number | null;
        cache_write_tokens?: number | null;
        input_tokens_breakdown: TurnStreamingOutputEventUsageInputTokensBreakdown.Raw;
    }
}
