// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TurnStateCancelledReason: core.serialization.Schema<
    serializers.TurnStateCancelledReason.Raw,
    TrueFoundryGateway.TurnStateCancelledReason
> = core.serialization.enum_(["server-execution-timeout", "client-cancelled", "cancelled-for-next-turn", "abandoned"]);

export declare namespace TurnStateCancelledReason {
    export type Raw = "server-execution-timeout" | "client-cancelled" | "cancelled-for-next-turn" | "abandoned";
}
