// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnOutputEventUsageInputTokensBreakdown } from "./TurnOutputEventUsageInputTokensBreakdown.js";

export const TurnOutputEventUsage: core.serialization.ObjectSchema<
    serializers.TurnOutputEventUsage.Raw,
    TrueFoundryGateway.TurnOutputEventUsage
> = core.serialization.object({
    input_tokens: core.serialization.number(),
    output_tokens: core.serialization.number(),
    cache_read_tokens: core.serialization.number().optional(),
    cache_write_tokens: core.serialization.number().optional(),
    input_tokens_breakdown: TurnOutputEventUsageInputTokensBreakdown,
});

export declare namespace TurnOutputEventUsage {
    export interface Raw {
        input_tokens: number;
        output_tokens: number;
        cache_read_tokens?: number | null;
        cache_write_tokens?: number | null;
        input_tokens_breakdown: TurnOutputEventUsageInputTokensBreakdown.Raw;
    }
}
