// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnOutputEventUsageInputTokensBreakdown } from "./TurnOutputEventUsageInputTokensBreakdown.js";

export const TurnOutputEventUsage: core.serialization.ObjectSchema<
    serializers.TurnOutputEventUsage.Raw,
    TrueFoundryGateway.TurnOutputEventUsage
> = core.serialization.object({
    inputTokens: core.serialization.property("input_tokens", core.serialization.number()),
    outputTokens: core.serialization.property("output_tokens", core.serialization.number()),
    cacheReadTokens: core.serialization.property("cache_read_tokens", core.serialization.number().optional()),
    cacheWriteTokens: core.serialization.property("cache_write_tokens", core.serialization.number().optional()),
    inputTokensBreakdown: core.serialization.property(
        "input_tokens_breakdown",
        TurnOutputEventUsageInputTokensBreakdown,
    ),
});

export declare namespace TurnOutputEventUsage {
    export interface Raw {
        input_tokens: number;
        output_tokens: number;
        cache_read_tokens?: number | null;
        cache_write_tokens?: number | null;
        input_tokens_breakdown: TurnOutputEventUsageInputTokensBreakdown.Raw;
    }
}
