// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentFinishReason } from "./AgentFinishReason.js";
import { AgentInfo } from "./AgentInfo.js";
import { AgentMcpInitializationInfo } from "./AgentMcpInitializationInfo.js";
import { AgentMcpServerAuthInfo } from "./AgentMcpServerAuthInfo.js";
import { AgentParent } from "./AgentParent.js";
import { AgentToolCallRef } from "./AgentToolCallRef.js";
import { ModelMessageEvent } from "./ModelMessageEvent.js";
import { TurnOutputEventAudio } from "./TurnOutputEventAudio.js";
import { TurnOutputEventFunctionCall } from "./TurnOutputEventFunctionCall.js";
import { TurnOutputEventThinkingBlocksItem } from "./TurnOutputEventThinkingBlocksItem.js";
import { TurnOutputEventUsage } from "./TurnOutputEventUsage.js";

export const TurnOutputEvent: core.serialization.ObjectSchema<
    serializers.TurnOutputEvent.Raw,
    TrueFoundryGateway.TurnOutputEvent
> = core.serialization.object({
    audio: TurnOutputEventAudio.optional(),
    content: core.serialization.list(AgentMcpInitializationInfo).optional(),
    functionCall: core.serialization.property("function_call", TurnOutputEventFunctionCall.optional()),
    name: core.serialization.string().optional(),
    refusal: core.serialization.string().optional(),
    thinkingBlocks: core.serialization.property(
        "thinking_blocks",
        core.serialization.list(TurnOutputEventThinkingBlocksItem).optional(),
    ),
    toolCalls: core.serialization.property("tool_calls", core.serialization.list(AgentToolCallRef).optional()),
    type: core.serialization.stringLiteral("tool.response_required").optional(),
    id: core.serialization.string().optional(),
    threadId: core.serialization.property("thread_id", core.serialization.string().optional()),
    finishReason: core.serialization.property("finish_reason", AgentFinishReason.optional()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    usage: TurnOutputEventUsage.optional(),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string().optional()),
    agentInfo: core.serialization.property("agent_info", AgentInfo.optional()),
    parent: AgentParent.optional(),
    title: core.serialization.string().optional(),
    output: ModelMessageEvent.optional(),
    status: core.serialization.stringLiteral("error").optional(),
    error: core.serialization.string().optional(),
    servers: core.serialization.list(AgentMcpServerAuthInfo).optional(),
    sandboxId: core.serialization.property("sandbox_id", core.serialization.string().optional()),
    sequenceNumber: core.serialization.property("sequence_number", core.serialization.number()),
});

export declare namespace TurnOutputEvent {
    export interface Raw {
        audio?: TurnOutputEventAudio.Raw | null;
        content?: AgentMcpInitializationInfo.Raw[] | null;
        function_call?: TurnOutputEventFunctionCall.Raw | null;
        name?: string | null;
        refusal?: string | null;
        thinking_blocks?: TurnOutputEventThinkingBlocksItem.Raw[] | null;
        tool_calls?: AgentToolCallRef.Raw[] | null;
        type?: "tool.response_required" | null;
        id?: string | null;
        thread_id?: string | null;
        finish_reason?: AgentFinishReason.Raw | null;
        created_at?: string | null;
        usage?: TurnOutputEventUsage.Raw | null;
        tool_call_id?: string | null;
        agent_info?: AgentInfo.Raw | null;
        parent?: AgentParent.Raw | null;
        title?: string | null;
        output?: ModelMessageEvent.Raw | null;
        status?: "error" | null;
        error?: string | null;
        servers?: AgentMcpServerAuthInfo.Raw[] | null;
        sandbox_id?: string | null;
        sequence_number: number;
    }
}
