// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TurnOutputEventAudio: core.serialization.ObjectSchema<
    serializers.TurnOutputEventAudio.Raw,
    TrueFoundryGateway.TurnOutputEventAudio
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace TurnOutputEventAudio {
    export interface Raw {
        id: string;
    }
}
