// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TurnDoneEventState } from "./TurnDoneEventState.js";

export const TurnDoneEvent: core.serialization.ObjectSchema<
    serializers.TurnDoneEvent.Raw,
    TrueFoundryGateway.TurnDoneEvent
> = core.serialization.object({
    id: core.serialization.string(),
    state: TurnDoneEventState,
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    threadId: core.serialization.property("thread_id", core.serialization.string().nullable()),
});

export declare namespace TurnDoneEvent {
    export interface Raw {
        id: string;
        state: TurnDoneEventState.Raw;
        created_at: string;
        thread_id?: string | null;
    }
}
