// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FileContent } from "./FileContent.js";
import { TextContent } from "./TextContent.js";

export const UserMessageContentItem: core.serialization.Schema<
    serializers.UserMessageContentItem.Raw,
    TrueFoundryGateway.UserMessageContentItem
> = core.serialization
    .union("type", {
        text: TextContent,
        file: FileContent,
    })
    .transform<TrueFoundryGateway.UserMessageContentItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace UserMessageContentItem {
    export type Raw = UserMessageContentItem.Text | UserMessageContentItem.File;

    export interface Text extends TextContent.Raw {
        type: "text";
    }

    export interface File extends FileContent.Raw {
        type: "file";
    }
}
