// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ApprovalDecision } from "./ApprovalDecision.js";

export const UserToolApprovalEvent: core.serialization.ObjectSchema<
    serializers.UserToolApprovalEvent.Raw,
    TrueFoundryGateway.UserToolApprovalEvent
> = core.serialization.object({
    type: core.serialization.stringLiteral("user.tool_approval"),
    threadId: core.serialization.property("thread_id", core.serialization.string()),
    toolCallId: core.serialization.property("tool_call_id", core.serialization.string()),
    approval: ApprovalDecision,
});

export declare namespace UserToolApprovalEvent {
    export interface Raw {
        type: "user.tool_approval";
        thread_id: string;
        tool_call_id: string;
        approval: ApprovalDecision.Raw;
    }
}
