// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentFileUploadContentPart } from "./AgentFileUploadContentPart.js";
import { AgentTextContentPart } from "./AgentTextContentPart.js";

export const UserMessageContentOneItem: core.serialization.Schema<
    serializers.UserMessageContentOneItem.Raw,
    TrueFoundryGateway.UserMessageContentOneItem
> = core.serialization.undiscriminatedUnion([AgentTextContentPart, AgentFileUploadContentPart]);

export declare namespace UserMessageContentOneItem {
    export type Raw = AgentTextContentPart.Raw | AgentFileUploadContentPart.Raw;
}
