// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agent_name: "agent_name"
 *     }
 */
export interface CreateSessionRequest {
    /** Name of an existing agent in the tenant. */
    agent_name: string;
}
