// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateTurnRequest {
    input?: TrueFoundryGateway.agents.CreateTurnRequestInputItem[];
    /** Defaults to 'auto' (chain to session last turn). Use 'null' for the session's first turn. */
    previous_turn_id?: TrueFoundryGateway.agents.CreateTurnRequestPreviousTurnId;
}
