// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../index.js";

/**
 * @example
 *     {
 *         pageToken: "page_token",
 *         limit: 1,
 *         order: "asc"
 *     }
 */
export interface SessionsListTurnEventsRequest {
    pageToken?: string;
    limit?: number;
    order?: TrueFoundryGateway.agents.SessionsListTurnEventsRequestOrder;
}
