// This file was auto-generated by Fern from our API Definition.

import * as TrueFoundryGateway from "../../../src/api/index";
import { TrueFoundryGatewayClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("SessionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    agent_name: "agent_name",
                    title: "title",
                    created_by_subject: { subject_id: "subject_id", subject_type: "subject_type" },
                    created_at: "created_at",
                    updated_at: "updated_at",
                },
            ],
            pagination: { next_page_token: "next_page_token", previous_page_token: "previous_page_token", limit: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/agents/sessions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.agents.sessions.list({
            agent_name: "agent_name",
            limit: 1,
            order: "asc",
            page_token: "page_token",
            start_timestamp: "start_timestamp",
            end_timestamp: "end_timestamp",
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.list({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.list({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.list({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.list({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.list({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.UnprocessableEntityError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_name: "agent_name" };
        const rawResponseBody = {
            data: {
                id: "id",
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                    subject_display_name: "subject_display_name",
                    subject_pat_name: "subject_pat_name",
                    subject_controller_name: "subject_controller_name",
                    subject_external_identity_slug: "subject_external_identity_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.sessions.create({
            agent_name: "agent_name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.create({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.create({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.create({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.create({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.create({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { agent_name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.create({
                agent_name: "x",
            });
        }).rejects.toThrow(TrueFoundryGateway.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                agent_name: "agent_name",
                title: "title",
                created_by_subject: {
                    subject_id: "subject_id",
                    subject_type: "subject_type",
                    subject_slug: "subject_slug",
                    subject_display_name: "subject_display_name",
                    subject_pat_name: "subject_pat_name",
                    subject_controller_name: "subject_controller_name",
                    subject_external_identity_slug: "subject_external_identity_slug",
                },
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.sessions.get("sessionId");
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.get("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.get("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.get("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("cancel (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/01arz3ndektsv4rrffq69g5fav.g/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.sessions.cancel("01arz3ndektsv4rrffq69g5fav.g");
        expect(response).toEqual(rawResponseBody);
    });

    test("cancel (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.cancel("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("cancel (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.cancel("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("cancel (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(412)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.cancel("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.PreconditionFailedError);
    });

    test("cancel (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(424)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.cancel("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.FailedDependencyError);
    });

    test("list_turns (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    session_id: "session_id",
                    first_turn_id: "first_turn_id",
                    previous_turn_id: "previous_turn_id",
                    state: { status: "running" },
                    input: [{ type: "user.message", content: "content" }],
                    created_at: "created_at",
                    updated_at: "updated_at",
                },
            ],
            pagination: { next_page_token: "next_page_token", previous_page_token: "previous_page_token", limit: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/agents/sessions/01arz3ndektsv4rrffq69g5fav.g/turns")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.agents.sessions.listTurns("01arz3ndektsv4rrffq69g5fav.g", {
            page_token: "page_token",
            limit: 1,
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list_turns (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId/turns")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.listTurns("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("list_turns (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId/turns")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.listTurns("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("create_turn (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody =
            'event: \ndata: {"audio":{"id":"id"},"content":[{"mcp_server_id":"mcp_server_id","mcp_server_name":"mcp_server_name","session_id":"session_id"}],"function_call":{"name":"name","arguments":"arguments"},"name":"name","refusal":"refusal","thinking_blocks":[{"type":"thinking","thinking":"thinking","signature":"signature"}],"tool_calls":[{"id":"id","source_event_id":"source_event_id"}],"type":"turn.created","id":"id","thread_id":"thread_id","finish_reason":"stop","created_at":"created_at","usage":{"input_tokens":1,"output_tokens":1,"cache_read_tokens":1,"cache_write_tokens":1,"input_tokens_breakdown":{"harness":1,"skills":1,"instructions":1,"tool_definitions":1,"messages":1}},"reasoning_content":"reasoning_content","tool_call_id":"tool_call_id","agent_info":{"type":"dynamic","name":"name","input":"input","model":"model"},"parent":{"thread_id":"thread_id","tool_call_id":"tool_call_id"},"title":"title","reason":"compaction","context":[{"role":"user","content":"content"}],"current_context_usage":{"completion_tokens":1,"prompt_tokens":1,"total_tokens":1,"completion_tokens_details":{"reasoning_tokens":1},"prompt_tokens_details":{"cached_tokens":1},"cache_read_input_tokens":1,"cache_creation_input_tokens":1},"compaction_llm_usage":{"completion_tokens":1,"prompt_tokens":1,"total_tokens":1,"completion_tokens_details":{"reasoning_tokens":1},"prompt_tokens_details":{"cached_tokens":1},"cache_read_input_tokens":1,"cache_creation_input_tokens":1},"servers":[{"mcp_server_id":"mcp_server_id","mcp_server_name":"mcp_server_name","auth_url":"auth_url","thread_ids":["thread_ids"]}],"sandbox_id":"sandbox_id","turn_id":"turn_id","previous_turn_id":"previous_turn_id","created_by":{"subject_id":"subject_id","subject_slug":"subject_slug","subject_type":"subject_type","tenant_name":"tenant_name"},"sequence_number":1}\n\n';

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/01arz3ndektsv4rrffq69g5fav.g/turns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.agents.sessions.createTurn("01arz3ndektsv4rrffq69g5fav.g");
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                audio: {
                    id: "id",
                },
                content: [
                    {
                        mcp_server_id: "mcp_server_id",
                        mcp_server_name: "mcp_server_name",
                        session_id: "session_id",
                    },
                ],
                function_call: {
                    name: "name",
                    arguments: "arguments",
                },
                name: "name",
                refusal: "refusal",
                thinking_blocks: [
                    {
                        type: "thinking",
                        thinking: "thinking",
                        signature: "signature",
                    },
                ],
                tool_calls: [
                    {
                        id: "id",
                        source_event_id: "source_event_id",
                    },
                ],
                type: "turn.created",
                id: "id",
                thread_id: "thread_id",
                finish_reason: "stop",
                created_at: "created_at",
                usage: {
                    input_tokens: 1,
                    output_tokens: 1,
                    cache_read_tokens: 1,
                    cache_write_tokens: 1,
                    input_tokens_breakdown: {
                        harness: 1,
                        skills: 1,
                        instructions: 1,
                        tool_definitions: 1,
                        messages: 1,
                    },
                },
                reasoning_content: "reasoning_content",
                tool_call_id: "tool_call_id",
                agent_info: {
                    type: "dynamic",
                    name: "name",
                    input: "input",
                    model: "model",
                },
                parent: {
                    thread_id: "thread_id",
                    tool_call_id: "tool_call_id",
                },
                title: "title",
                reason: "compaction",
                context: [
                    {
                        role: "user",
                        content: "content",
                    },
                ],
                current_context_usage: {
                    completion_tokens: 1,
                    prompt_tokens: 1,
                    total_tokens: 1,
                    completion_tokens_details: {
                        reasoning_tokens: 1,
                    },
                    prompt_tokens_details: {
                        cached_tokens: 1,
                    },
                    cache_read_input_tokens: 1,
                    cache_creation_input_tokens: 1,
                },
                compaction_llm_usage: {
                    completion_tokens: 1,
                    prompt_tokens: 1,
                    total_tokens: 1,
                    completion_tokens_details: {
                        reasoning_tokens: 1,
                    },
                    prompt_tokens_details: {
                        cached_tokens: 1,
                    },
                    cache_read_input_tokens: 1,
                    cache_creation_input_tokens: 1,
                },
                servers: [
                    {
                        mcp_server_id: "mcp_server_id",
                        mcp_server_name: "mcp_server_name",
                        auth_url: "auth_url",
                        thread_ids: ["thread_ids"],
                    },
                ],
                sandbox_id: "sandbox_id",
                turn_id: "turn_id",
                previous_turn_id: "previous_turn_id",
                created_by: {
                    subject_id: "subject_id",
                    subject_slug: "subject_slug",
                    subject_type: "subject_type",
                    tenant_name: "tenant_name",
                },
                sequence_number: 1,
            },
        ]);
    });

    test("create_turn (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/turns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.createTurn("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("create_turn (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/turns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.createTurn("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.ForbiddenError);
    });

    test("create_turn (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/turns")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.createTurn("sessionId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("get_turn (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: {
                id: "id",
                session_id: "session_id",
                first_turn_id: "first_turn_id",
                previous_turn_id: "previous_turn_id",
                state: { status: "running" },
                input: [{ type: "user.message", content: "content" }],
                created_at: "created_at",
                updated_at: "updated_at",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/01arz3ndektsv4rrffq69g5fav.g/turns/01arz3ndektsv4rrffq69g5fav.g.ab12cd")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.sessions.getTurn(
            "01arz3ndektsv4rrffq69g5fav.g",
            "01arz3ndektsv4rrffq69g5fav.g.ab12cd",
        );
        expect(response).toEqual(rawResponseBody);
    });

    test("get_turn (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId/turns/turnId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.getTurn("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("get_turn (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId/turns/turnId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.getTurn("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("subscribe_to_turn (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody =
            'event: \ndata: {"audio":{"id":"id"},"content":[{"mcp_server_id":"mcp_server_id","mcp_server_name":"mcp_server_name","session_id":"session_id"}],"function_call":{"name":"name","arguments":"arguments"},"name":"name","refusal":"refusal","thinking_blocks":[{"type":"thinking","thinking":"thinking","signature":"signature"}],"tool_calls":[{"id":"id","source_event_id":"source_event_id"}],"type":"turn.created","id":"id","thread_id":"thread_id","finish_reason":"stop","created_at":"created_at","usage":{"input_tokens":1,"output_tokens":1,"cache_read_tokens":1,"cache_write_tokens":1,"input_tokens_breakdown":{"harness":1,"skills":1,"instructions":1,"tool_definitions":1,"messages":1}},"reasoning_content":"reasoning_content","tool_call_id":"tool_call_id","agent_info":{"type":"dynamic","name":"name","input":"input","model":"model"},"parent":{"thread_id":"thread_id","tool_call_id":"tool_call_id"},"title":"title","reason":"compaction","context":[{"role":"user","content":"content"}],"current_context_usage":{"completion_tokens":1,"prompt_tokens":1,"total_tokens":1,"completion_tokens_details":{"reasoning_tokens":1},"prompt_tokens_details":{"cached_tokens":1},"cache_read_input_tokens":1,"cache_creation_input_tokens":1},"compaction_llm_usage":{"completion_tokens":1,"prompt_tokens":1,"total_tokens":1,"completion_tokens_details":{"reasoning_tokens":1},"prompt_tokens_details":{"cached_tokens":1},"cache_read_input_tokens":1,"cache_creation_input_tokens":1},"servers":[{"mcp_server_id":"mcp_server_id","mcp_server_name":"mcp_server_name","auth_url":"auth_url","thread_ids":["thread_ids"]}],"sandbox_id":"sandbox_id","turn_id":"turn_id","previous_turn_id":"previous_turn_id","created_by":{"subject_id":"subject_id","subject_slug":"subject_slug","subject_type":"subject_type","tenant_name":"tenant_name"},"sequence_number":1}\n\n';

        server
            .mockEndpoint()
            .post(
                "/v1/agents/sessions/01arz3ndektsv4rrffq69g5fav.g/turns/01arz3ndektsv4rrffq69g5fav.g.ab12cd/subscribe",
            )
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.agents.sessions.subscribeToTurn(
            "01arz3ndektsv4rrffq69g5fav.g",
            "01arz3ndektsv4rrffq69g5fav.g.ab12cd",
        );
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                audio: {
                    id: "id",
                },
                content: [
                    {
                        mcp_server_id: "mcp_server_id",
                        mcp_server_name: "mcp_server_name",
                        session_id: "session_id",
                    },
                ],
                function_call: {
                    name: "name",
                    arguments: "arguments",
                },
                name: "name",
                refusal: "refusal",
                thinking_blocks: [
                    {
                        type: "thinking",
                        thinking: "thinking",
                        signature: "signature",
                    },
                ],
                tool_calls: [
                    {
                        id: "id",
                        source_event_id: "source_event_id",
                    },
                ],
                type: "turn.created",
                id: "id",
                thread_id: "thread_id",
                finish_reason: "stop",
                created_at: "created_at",
                usage: {
                    input_tokens: 1,
                    output_tokens: 1,
                    cache_read_tokens: 1,
                    cache_write_tokens: 1,
                    input_tokens_breakdown: {
                        harness: 1,
                        skills: 1,
                        instructions: 1,
                        tool_definitions: 1,
                        messages: 1,
                    },
                },
                reasoning_content: "reasoning_content",
                tool_call_id: "tool_call_id",
                agent_info: {
                    type: "dynamic",
                    name: "name",
                    input: "input",
                    model: "model",
                },
                parent: {
                    thread_id: "thread_id",
                    tool_call_id: "tool_call_id",
                },
                title: "title",
                reason: "compaction",
                context: [
                    {
                        role: "user",
                        content: "content",
                    },
                ],
                current_context_usage: {
                    completion_tokens: 1,
                    prompt_tokens: 1,
                    total_tokens: 1,
                    completion_tokens_details: {
                        reasoning_tokens: 1,
                    },
                    prompt_tokens_details: {
                        cached_tokens: 1,
                    },
                    cache_read_input_tokens: 1,
                    cache_creation_input_tokens: 1,
                },
                compaction_llm_usage: {
                    completion_tokens: 1,
                    prompt_tokens: 1,
                    total_tokens: 1,
                    completion_tokens_details: {
                        reasoning_tokens: 1,
                    },
                    prompt_tokens_details: {
                        cached_tokens: 1,
                    },
                    cache_read_input_tokens: 1,
                    cache_creation_input_tokens: 1,
                },
                servers: [
                    {
                        mcp_server_id: "mcp_server_id",
                        mcp_server_name: "mcp_server_name",
                        auth_url: "auth_url",
                        thread_ids: ["thread_ids"],
                    },
                ],
                sandbox_id: "sandbox_id",
                turn_id: "turn_id",
                previous_turn_id: "previous_turn_id",
                created_by: {
                    subject_id: "subject_id",
                    subject_slug: "subject_slug",
                    subject_type: "subject_type",
                    tenant_name: "tenant_name",
                },
                sequence_number: 1,
            },
        ]);
    });

    test("subscribe_to_turn (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/turns/turnId/subscribe")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.subscribeToTurn("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("subscribe_to_turn (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/turns/turnId/subscribe")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.subscribeToTurn("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("subscribe_to_turn (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/turns/turnId/subscribe")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(412)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.subscribeToTurn("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.PreconditionFailedError);
    });

    test("subscribe_to_turn (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/agents/sessions/sessionId/turns/turnId/subscribe")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(504)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.subscribeToTurn("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.GatewayTimeoutError);
    });

    test("list_turn_events (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    audio: { id: "id" },
                    content: [{ mcp_server_id: "mcp_server_id", mcp_server_name: "mcp_server_name" }],
                    function_call: { name: "name", arguments: "arguments" },
                    name: "name",
                    refusal: "refusal",
                    thinking_blocks: [{ type: "thinking", thinking: "thinking" }],
                    tool_calls: [{ id: "id", source_event_id: "source_event_id" }],
                    type: "tool.response_required",
                    id: "id",
                    thread_id: "thread_id",
                    finish_reason: "stop",
                    created_at: "created_at",
                    usage: {
                        input_tokens: 1,
                        output_tokens: 1,
                        input_tokens_breakdown: {
                            harness: 1,
                            skills: 1,
                            instructions: 1,
                            tool_definitions: 1,
                            messages: 1,
                        },
                    },
                    tool_call_id: "tool_call_id",
                    agent_info: { type: "dynamic", name: "name", input: "input" },
                    parent: { thread_id: "thread_id", tool_call_id: "tool_call_id" },
                    title: "title",
                    output: { type: "model.message", id: "id", thread_id: "thread_id", created_at: "created_at" },
                    status: "error",
                    error: "error",
                    servers: [
                        {
                            mcp_server_id: "mcp_server_id",
                            mcp_server_name: "mcp_server_name",
                            auth_url: "auth_url",
                            thread_ids: ["thread_ids"],
                        },
                    ],
                    sandbox_id: "sandbox_id",
                    sequence_number: 1,
                },
            ],
            pagination: {
                next_page_token: "next_page_token",
                previous_page_token: "previous_page_token",
                limit: 1,
                order: "asc",
            },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/agents/sessions/01arz3ndektsv4rrffq69g5fav.g/turns/01arz3ndektsv4rrffq69g5fav.g.ab12cd/events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.agents.sessions.listTurnEvents(
            "01arz3ndektsv4rrffq69g5fav.g",
            "01arz3ndektsv4rrffq69g5fav.g.ab12cd",
            {
                page_token: "page_token",
                limit: 1,
                order: "asc",
            },
        );

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list_turn_events (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId/turns/turnId/events")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.listTurnEvents("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.BadRequestError);
    });

    test("list_turn_events (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId/turns/turnId/events")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.listTurnEvents("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.NotFoundError);
    });

    test("list_turn_events (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueFoundryGatewayClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/agents/sessions/sessionId/turns/turnId/events")
            .respondWith()
            .statusCode(412)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.sessions.listTurnEvents("sessionId", "turnId");
        }).rejects.toThrow(TrueFoundryGateway.PreconditionFailedError);
    });
});
