// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../../../BaseClient.js";
import {
    type NormalizedClientOptionsWithAuth,
    normalizeClientOptionsWithAuth,
} from "../../../../../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../../../errors/index.js";
import * as serializers from "../../../../../../../../../../serialization/index.js";
import * as TrueFoundryGateway from "../../../../../../../../../index.js";

export declare namespace SessionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SessionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SessionsClient.Options>;

    constructor(options: SessionsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List all sessions owned by the caller, spanning both saved sessions and drafts (newest first by default), keyset-paginated. Optionally filter by `agent_name`. Pass `page_token` to fetch the next page, keeping the other query params constant.
     *
     * @param {TrueFoundryGateway.private_.agents.private_.SessionsListOwnedSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.BadRequestError}
     * @throws {@link TrueFoundryGateway.UnauthorizedError}
     * @throws {@link TrueFoundryGateway.NotFoundError}
     * @throws {@link TrueFoundryGateway.UnprocessableEntityError}
     *
     * @example
     *     await client.private.agents.private.sessions.listOwnedSessions({
     *         agentName: "agent_name",
     *         limit: 1,
     *         order: "asc",
     *         pageToken: "page_token",
     *         startTimestamp: "start_timestamp",
     *         endTimestamp: "end_timestamp"
     *     })
     */
    public async listOwnedSessions(
        request: TrueFoundryGateway.private_.agents.private_.SessionsListOwnedSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<
        core.Page<TrueFoundryGateway.ListOwnedSessionsResponseDataItem, TrueFoundryGateway.ListOwnedSessionsResponse>
    > {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueFoundryGateway.private_.agents.private_.SessionsListOwnedSessionsRequest,
            ): Promise<core.WithRawResponse<TrueFoundryGateway.ListOwnedSessionsResponse>> => {
                const { agentName, limit = 10, order, pageToken, startTimestamp, endTimestamp } = request;
                const _queryParams: Record<string, unknown> = {
                    agent_name: agentName,
                    limit,
                    order:
                        order != null
                            ? serializers.ListOwnedSessionsOrder.jsonOrThrow(order, {
                                  unrecognizedObjectKeys: "passthrough",
                                  allowUnrecognizedUnionMembers: true,
                                  allowUnrecognizedEnumValues: true,
                                  omitUndefined: true,
                              })
                            : undefined,
                    page_token: pageToken,
                    start_timestamp: startTimestamp,
                    end_timestamp: endTimestamp,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        "v1/x/agents/sessions/owned-sessions",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListOwnedSessionsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueFoundryGateway.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 401:
                            throw new TrueFoundryGateway.UnauthorizedError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new TrueFoundryGateway.NotFoundError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 422:
                            throw new TrueFoundryGateway.UnprocessableEntityError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueFoundryGatewayError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/x/agents/sessions/owned-sessions",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<
            TrueFoundryGateway.ListOwnedSessionsResponseDataItem,
            TrueFoundryGateway.ListOwnedSessionsResponse
        >({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }
}
