// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         agentName: "agent_name"
 *     }
 */
export interface CreateSessionRequest {
    /** Name of an existing agent in the tenant. */
    agentName: string;
}
