// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         sessionId: "01arz3ndektsv4rrffq69g5fav.g",
 *         turnId: "01arz3ndektsv4rrffq69g5fav.g.ab12cd"
 *     }
 */
export interface ListTurnEventsSessionsRequest {
    sessionId: string;
    turnId: string;
    pageToken?: string;
    /** Page size. Defaults to 25, max 25. */
    limit?: number;
    /** Sort events by creation time. Defaults to "asc". */
    order?: TrueFoundryGateway.ListEventsOrder;
}
