// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sessionId: "01arz3ndektsv4rrffq69g5fav.g"
 *     }
 */
export interface ListTurnsSessionsRequest {
    sessionId: string;
    pageToken?: string;
    /** Page size. Defaults to 10, max 25. */
    limit?: number;
}
