// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         pageToken: "page_token",
 *         limit: 1,
 *         order: "asc"
 *     }
 */
export interface SessionsListTurnEventsRequest {
    pageToken?: string;
    /** Page size. Defaults to 25, max 25. */
    limit?: number;
    /** Sort events by creation time. Defaults to "asc". */
    order?: TrueFoundryGateway.ListEventsOrder;
}
