// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import {
    type NormalizedClientOptionsWithAuth,
    normalizeClientOptionsWithAuth,
} from "../../../../../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../errors/index.js";
import * as serializers from "../../../../../../../../serialization/index.js";
import * as TrueFoundryGateway from "../../../../../../../index.js";

export declare namespace SessionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SessionsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SessionsClient.Options>;

    constructor(options: SessionsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List sessions for an agent (newest first by default), keyset-paginated. Pass `page_token` to fetch the next page, keeping the other query params constant.
     *
     * @param {TrueFoundryGateway.private_.agents.ListSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.BadRequestError}
     * @throws {@link TrueFoundryGateway.UnauthorizedError}
     * @throws {@link TrueFoundryGateway.ForbiddenError}
     * @throws {@link TrueFoundryGateway.NotFoundError}
     * @throws {@link TrueFoundryGateway.UnprocessableEntityError}
     * @throws {@link errors.TrueFoundryGatewayError}
     * @throws {@link errors.TrueFoundryGatewayTimeoutError}
     *
     * @example
     *     await client.private.agents.sessions.list({
     *         agentName: "agent_name"
     *     })
     */
    public async list(
        request: TrueFoundryGateway.private_.agents.ListSessionsRequest,
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.Page<TrueFoundryGateway.Session, TrueFoundryGateway.ListSessionsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueFoundryGateway.private_.agents.ListSessionsRequest,
            ): Promise<core.WithRawResponse<TrueFoundryGateway.ListSessionsResponse>> => {
                const { agentName, limit = 10, order, pageToken, startTimestamp, endTimestamp } = request;
                const _queryParams: Record<string, unknown> = {
                    agent_name: agentName,
                    limit,
                    order:
                        order != null
                            ? serializers.ListSessionsOrder.jsonOrThrow(order, {
                                  unrecognizedObjectKeys: "passthrough",
                                  allowUnrecognizedUnionMembers: true,
                                  allowUnrecognizedEnumValues: true,
                                  omitUndefined: true,
                              })
                            : undefined,
                    page_token: pageToken,
                    start_timestamp: startTimestamp,
                    end_timestamp: endTimestamp,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        "v1/agents/sessions",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListSessionsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueFoundryGateway.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 401:
                            throw new TrueFoundryGateway.UnauthorizedError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 403:
                            throw new TrueFoundryGateway.ForbiddenError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new TrueFoundryGateway.NotFoundError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 422:
                            throw new TrueFoundryGateway.UnprocessableEntityError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueFoundryGatewayError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/agents/sessions");
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueFoundryGateway.Session, TrueFoundryGateway.ListSessionsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * Create a session for an existing named agent.
     *
     * @param {TrueFoundryGateway.private_.agents.CreateSessionRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.BadRequestError}
     * @throws {@link TrueFoundryGateway.UnauthorizedError}
     * @throws {@link TrueFoundryGateway.ForbiddenError}
     * @throws {@link TrueFoundryGateway.NotFoundError}
     * @throws {@link TrueFoundryGateway.ConflictError}
     * @throws {@link TrueFoundryGateway.UnprocessableEntityError}
     * @throws {@link errors.TrueFoundryGatewayError}
     * @throws {@link errors.TrueFoundryGatewayTimeoutError}
     *
     * @example
     *     await client.private.agents.sessions.create({
     *         agentName: "agent_name"
     *     })
     */
    public create(
        request: TrueFoundryGateway.private_.agents.CreateSessionRequest,
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundryGateway.GetSessionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: TrueFoundryGateway.private_.agents.CreateSessionRequest,
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundryGateway.GetSessionResponse>> {
        const { tfyMetadata, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "x-tfy-metadata": tfyMetadata }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "v1/agents/sessions",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.private_.agents.CreateSessionRequest.jsonOrThrow(_body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetSessionResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueFoundryGateway.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 401:
                    throw new TrueFoundryGateway.UnauthorizedError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new TrueFoundryGateway.ForbiddenError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueFoundryGateway.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 409:
                    throw new TrueFoundryGateway.ConflictError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 422:
                    throw new TrueFoundryGateway.UnprocessableEntityError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryGatewayError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/agents/sessions");
    }

    /**
     * Get a session by id. Visible to the session owner or a manager of the session agent.
     *
     * @param {string} sessionId - Session identifier.
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.UnauthorizedError}
     * @throws {@link TrueFoundryGateway.ForbiddenError}
     * @throws {@link TrueFoundryGateway.NotFoundError}
     * @throws {@link errors.TrueFoundryGatewayError}
     * @throws {@link errors.TrueFoundryGatewayTimeoutError}
     *
     * @example
     *     await client.private.agents.sessions.get("sessionId")
     */
    public get(
        sessionId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundryGateway.GetSessionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(sessionId, requestOptions));
    }

    private async __get(
        sessionId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundryGateway.GetSessionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/agents/sessions/${core.url.encodePathParam(sessionId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetSessionResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new TrueFoundryGateway.UnauthorizedError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new TrueFoundryGateway.ForbiddenError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueFoundryGateway.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryGatewayError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/agents/sessions/{sessionId}",
        );
    }

    /**
     * Cancel the running last turn for a session.
     *
     * @param {string} sessionId
     * @param {TrueFoundryGateway.private_.agents.CancelSessionRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.BadRequestError}
     * @throws {@link TrueFoundryGateway.PreconditionFailedError}
     * @throws {@link TrueFoundryGateway.FailedDependencyError}
     * @throws {@link errors.TrueFoundryGatewayError}
     * @throws {@link errors.TrueFoundryGatewayTimeoutError}
     *
     * @example
     *     await client.private.agents.sessions.cancel("01arz3ndektsv4rrffq69g5fav.g")
     */
    public cancel(
        sessionId: string,
        request: TrueFoundryGateway.private_.agents.CancelSessionRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundryGateway.CancelSessionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__cancel(sessionId, request, requestOptions));
    }

    private async __cancel(
        sessionId: string,
        request: TrueFoundryGateway.private_.agents.CancelSessionRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundryGateway.CancelSessionResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/agents/sessions/${core.url.encodePathParam(sessionId)}/cancel`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.private_.agents.CancelSessionRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CancelSessionResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueFoundryGateway.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 412:
                    throw new TrueFoundryGateway.PreconditionFailedError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 424:
                    throw new TrueFoundryGateway.FailedDependencyError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryGatewayError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/agents/sessions/{sessionId}/cancel",
        );
    }

    /**
     * List turns for a session (newest first). Pagination walks the ancestor chain from the session last turn, or from the turn in page_token when continuing.
     *
     * @param {string} sessionId
     * @param {TrueFoundryGateway.private_.agents.ListTurnsSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.BadRequestError}
     * @throws {@link TrueFoundryGateway.NotFoundError}
     * @throws {@link TrueFoundryGateway.PreconditionFailedError}
     * @throws {@link errors.TrueFoundryGatewayError}
     * @throws {@link errors.TrueFoundryGatewayTimeoutError}
     *
     * @example
     *     await client.private.agents.sessions.listTurns("01arz3ndektsv4rrffq69g5fav.g")
     */
    public async listTurns(
        sessionId: string,
        request: TrueFoundryGateway.private_.agents.ListTurnsSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.Page<TrueFoundryGateway.Turn, TrueFoundryGateway.ListTurnsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueFoundryGateway.private_.agents.ListTurnsSessionsRequest,
            ): Promise<core.WithRawResponse<TrueFoundryGateway.ListTurnsResponse>> => {
                const { pageToken, limit = 10 } = request;
                const _queryParams: Record<string, unknown> = {
                    page_token: pageToken,
                    limit,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        `v1/agents/sessions/${core.url.encodePathParam(sessionId)}/turns`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListTurnsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueFoundryGateway.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new TrueFoundryGateway.NotFoundError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 412:
                            throw new TrueFoundryGateway.PreconditionFailedError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueFoundryGatewayError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/agents/sessions/{sessionId}/turns",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueFoundryGateway.Turn, TrueFoundryGateway.ListTurnsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * Start or continue a turn within a session. Responds with a Server-Sent Events stream.
     * Use `previous_turn_id` to chain to the session's last turn (defaults to `auto`).
     */
    public createTurn(
        sessionId: string,
        request: TrueFoundryGateway.private_.agents.CreateTurnRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<core.Stream<TrueFoundryGateway.TurnStreamingEvent>> {
        return core.HttpResponsePromise.fromPromise(this.__createTurn(sessionId, request, requestOptions));
    }

    private async __createTurn(
        sessionId: string,
        request: TrueFoundryGateway.private_.agents.CreateTurnRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.Stream<TrueFoundryGateway.TurnStreamingEvent>>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)<ReadableStream>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/agents/sessions/${core.url.encodePathParam(sessionId)}/turns`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.private_.agents.CreateTurnRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            responseType: "sse",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: new core.Stream({
                    stream: _response.body,
                    parse: async (data) => {
                        return serializers.TurnStreamingEvent.parseOrThrow(data, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        });
                    },
                    signal: requestOptions?.abortSignal,
                    eventShape: {
                        type: "sse",
                    },
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueFoundryGateway.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 403:
                    throw new TrueFoundryGateway.ForbiddenError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueFoundryGateway.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 412:
                    throw new TrueFoundryGateway.PreconditionFailedError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryGatewayError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/agents/sessions/{sessionId}/turns",
        );
    }

    /**
     * Get a single turn by ID from Redis.
     *
     * @param {string} sessionId
     * @param {string} turnId
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.BadRequestError}
     * @throws {@link TrueFoundryGateway.NotFoundError}
     * @throws {@link errors.TrueFoundryGatewayError}
     * @throws {@link errors.TrueFoundryGatewayTimeoutError}
     *
     * @example
     *     await client.private.agents.sessions.getTurn("01arz3ndektsv4rrffq69g5fav.g", "01arz3ndektsv4rrffq69g5fav.g.ab12cd")
     */
    public getTurn(
        sessionId: string,
        turnId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<TrueFoundryGateway.GetTurnResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTurn(sessionId, turnId, requestOptions));
    }

    private async __getTurn(
        sessionId: string,
        turnId: string,
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<TrueFoundryGateway.GetTurnResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/agents/sessions/${core.url.encodePathParam(sessionId)}/turns/${core.url.encodePathParam(turnId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetTurnResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueFoundryGateway.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueFoundryGateway.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryGatewayError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/agents/sessions/{sessionId}/turns/{turnId}",
        );
    }

    /**
     * Subscribe to the live SSE stream for a turn. Pass after_sequence_number to resume after disconnect or server timeout, or send Last-Event-Id when after_sequence_number is omitted.
     */
    public subscribeToTurn(
        sessionId: string,
        turnId: string,
        request: TrueFoundryGateway.private_.agents.SubscribeTurnRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): core.HttpResponsePromise<core.Stream<TrueFoundryGateway.TurnStreamingEvent>> {
        return core.HttpResponsePromise.fromPromise(this.__subscribeToTurn(sessionId, turnId, request, requestOptions));
    }

    private async __subscribeToTurn(
        sessionId: string,
        turnId: string,
        request: TrueFoundryGateway.private_.agents.SubscribeTurnRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.Stream<TrueFoundryGateway.TurnStreamingEvent>>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)<ReadableStream>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `v1/agents/sessions/${core.url.encodePathParam(sessionId)}/turns/${core.url.encodePathParam(turnId)}/subscribe`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(
                serializers.private_.agents.SubscribeTurnRequest.jsonOrThrow(request, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    omitUndefined: true,
                }),
                requestOptions?.additionalBodyParameters,
            ),
            responseType: "sse",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        const _reconnect = async (lastEventId: string) => {
            const _reconnectResponse = await (this._options.fetcher ?? core.fetcher)<ReadableStream>({
                url: core.url.join(
                    (await core.Supplier.get(this._options.baseUrl)) ??
                        (await core.Supplier.get(this._options.environment)),
                    `v1/agents/sessions/${core.url.encodePathParam(sessionId)}/turns/${core.url.encodePathParam(turnId)}/subscribe`,
                ),
                method: "POST",
                headers: { ..._headers, "Last-Event-ID": lastEventId },
                contentType: "application/json",
                queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
                requestType: "json",
                body: mergeAdditionalBodyParameters(
                    serializers.private_.agents.SubscribeTurnRequest.jsonOrThrow(request, {
                        unrecognizedObjectKeys: "passthrough",
                        allowUnrecognizedUnionMembers: true,
                        allowUnrecognizedEnumValues: true,
                        omitUndefined: true,
                    }),
                    requestOptions?.additionalBodyParameters,
                ),
                responseType: "sse",
                timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                abortSignal: requestOptions?.abortSignal,
                fetchFn: this._options?.fetch,
                logging: this._options.logging,
            });
            if (!_reconnectResponse.ok) {
                throw new Error("SSE stream reconnection failed");
            }
            if (_reconnectResponse.body == null) {
                throw new Error("SSE stream reconnection failed: empty response body");
            }
            return _reconnectResponse.body;
        };
        if (_response.ok) {
            return {
                data: new core.Stream({
                    stream: _response.body,
                    parse: async (data) => {
                        return serializers.TurnStreamingEvent.parseOrThrow(data, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        });
                    },
                    signal: requestOptions?.abortSignal,
                    eventShape: {
                        type: "sse",
                        resumable: true,
                    },
                    reconnectionEnabled:
                        requestOptions?.stream?.reconnectionEnabled ?? this._options?.stream?.reconnectionEnabled,
                    maxReconnectionAttempts:
                        requestOptions?.stream?.maxReconnectionAttempts ??
                        this._options?.stream?.maxReconnectionAttempts,
                    reconnect: _reconnect,
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new TrueFoundryGateway.BadRequestError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 404:
                    throw new TrueFoundryGateway.NotFoundError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 412:
                    throw new TrueFoundryGateway.PreconditionFailedError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                case 504:
                    throw new TrueFoundryGateway.GatewayTimeoutError(
                        serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.TrueFoundryGatewayError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/agents/sessions/{sessionId}/turns/{turnId}/subscribe",
        );
    }

    /**
     * Paginated list of content turn events from the Redis events stream (model.message, tool.call, …). `turn.created` and `turn.done` are stored in the stream but excluded from this endpoint — use session list_events for lifecycle. Only available after the turn has reached a terminal state; use subscribe for running turns.
     *
     * @param {string} sessionId
     * @param {string} turnId
     * @param {TrueFoundryGateway.private_.agents.ListTurnEventsSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.BadRequestError}
     * @throws {@link TrueFoundryGateway.NotFoundError}
     * @throws {@link TrueFoundryGateway.ConflictError}
     * @throws {@link TrueFoundryGateway.PreconditionFailedError}
     * @throws {@link errors.TrueFoundryGatewayError}
     * @throws {@link errors.TrueFoundryGatewayTimeoutError}
     *
     * @example
     *     await client.private.agents.sessions.listTurnEvents("01arz3ndektsv4rrffq69g5fav.g", "01arz3ndektsv4rrffq69g5fav.g.ab12cd")
     */
    public async listTurnEvents(
        sessionId: string,
        turnId: string,
        request: TrueFoundryGateway.private_.agents.ListTurnEventsSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.Page<TrueFoundryGateway.TurnEvent, TrueFoundryGateway.ListEventsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueFoundryGateway.private_.agents.ListTurnEventsSessionsRequest,
            ): Promise<core.WithRawResponse<TrueFoundryGateway.ListEventsResponse>> => {
                const { pageToken, limit = 25, order } = request;
                const _queryParams: Record<string, unknown> = {
                    page_token: pageToken,
                    limit,
                    order:
                        order != null
                            ? serializers.ListEventsOrder.jsonOrThrow(order, {
                                  unrecognizedObjectKeys: "passthrough",
                                  allowUnrecognizedUnionMembers: true,
                                  allowUnrecognizedEnumValues: true,
                                  omitUndefined: true,
                              })
                            : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        `v1/agents/sessions/${core.url.encodePathParam(sessionId)}/turns/${core.url.encodePathParam(turnId)}/events`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListEventsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueFoundryGateway.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new TrueFoundryGateway.NotFoundError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 409:
                            throw new TrueFoundryGateway.ConflictError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 412:
                            throw new TrueFoundryGateway.PreconditionFailedError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueFoundryGatewayError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/agents/sessions/{sessionId}/turns/{turnId}/events",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueFoundryGateway.TurnEvent, TrueFoundryGateway.ListEventsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }

    /**
     * List session events as `{ turn_id, event }` across a turn hierarchy (newest first). Each turn contributes turn.created, content events (model.message, tool.call, …), and turn.done; streaming deltas are not included. `last_turn_id` (initial load only) sets the newest turn in the window plus its ancestors; omit to use the session last turn. If that turn is still running, it is excluded — listing anchors on its parent so persisted events are returned without overlapping the live stream; subscribe to the running turn for live events. An empty `data` array is returned when the anchor is a running first turn with no parent. Use `page_token` to paginate backward toward older events; chains longer than the stored ancestor window are walked via spill to the session root.
     *
     * @param {string} sessionId
     * @param {TrueFoundryGateway.private_.agents.ListEventsSessionsRequest} request
     * @param {SessionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link TrueFoundryGateway.BadRequestError}
     * @throws {@link TrueFoundryGateway.NotFoundError}
     * @throws {@link TrueFoundryGateway.PreconditionFailedError}
     * @throws {@link errors.TrueFoundryGatewayError}
     * @throws {@link errors.TrueFoundryGatewayTimeoutError}
     *
     * @example
     *     await client.private.agents.sessions.listEvents("01arz3ndektsv4rrffq69g5fav.g")
     */
    public async listEvents(
        sessionId: string,
        request: TrueFoundryGateway.private_.agents.ListEventsSessionsRequest = {},
        requestOptions?: SessionsClient.RequestOptions,
    ): Promise<core.Page<TrueFoundryGateway.SessionEventItem, TrueFoundryGateway.ListSessionEventsResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: TrueFoundryGateway.private_.agents.ListEventsSessionsRequest,
            ): Promise<core.WithRawResponse<TrueFoundryGateway.ListSessionEventsResponse>> => {
                const { pageToken, lastTurnId, limit = 100 } = request;
                const _queryParams: Record<string, unknown> = {
                    page_token: pageToken,
                    last_turn_id: lastTurnId,
                    limit,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)),
                        `v1/agents/sessions/${core.url.encodePathParam(sessionId)}/events`,
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: serializers.ListSessionEventsResponse.parseOrThrow(_response.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new TrueFoundryGateway.BadRequestError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 404:
                            throw new TrueFoundryGateway.NotFoundError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        case 412:
                            throw new TrueFoundryGateway.PreconditionFailedError(
                                serializers.RequestErrorResponse.parseOrThrow(_response.error.body, {
                                    unrecognizedObjectKeys: "passthrough",
                                    allowUnrecognizedUnionMembers: true,
                                    allowUnrecognizedEnumValues: true,
                                    skipValidation: true,
                                    breadcrumbsPrefix: ["response"],
                                }),
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.TrueFoundryGatewayError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(
                    _response.error,
                    _response.rawResponse,
                    "GET",
                    "/v1/agents/sessions/{sessionId}/events",
                );
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<TrueFoundryGateway.SessionEventItem, TrueFoundryGateway.ListSessionEventsResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.pagination.nextPageToken != null &&
                !(typeof response?.pagination.nextPageToken === "string" && response?.pagination.nextPageToken === ""),
            getItems: (response) => response?.data ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "pageToken", response?.pagination.nextPageToken));
            },
        });
    }
}
