// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { DraftSession } from "../../../../../../../types/DraftSession.js";

export const DraftSessionsGetResponse: core.serialization.ObjectSchema<
    serializers.private_.agents.DraftSessionsGetResponse.Raw,
    TrueFoundryGateway.private_.agents.DraftSessionsGetResponse
> = core.serialization.object({
    data: DraftSession,
});

export declare namespace DraftSessionsGetResponse {
    export interface Raw {
        data: DraftSession.Raw;
    }
}
