// This file was auto-generated by Fern from our API Definition.

import type * as TrueFoundryGateway from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { DraftSession } from "../../../../../../../types/DraftSession.js";
import { TokenPagination } from "../../../../../../../types/TokenPagination.js";

export const DraftSessionsListResponse: core.serialization.ObjectSchema<
    serializers.private_.agents.DraftSessionsListResponse.Raw,
    TrueFoundryGateway.private_.agents.DraftSessionsListResponse
> = core.serialization.object({
    data: core.serialization.list(DraftSession),
    pagination: TokenPagination,
});

export declare namespace DraftSessionsListResponse {
    export interface Raw {
        data: DraftSession.Raw[];
        pagination: TokenPagination.Raw;
    }
}
